import PEL4.ModalDynamicsIntermediatePhase
import PEL4.PopulationAxiology.PopulationProspect

namespace PEL4.PopulationAxiology

/-!
# Rational four-cell evidence kernels

An outcome prospect and an evidence profile are different simplexes. This
module models a point of the evidence simplex `Delta^3` by four nonnegative
rational cell masses summing to one. The cells are ordered `T`, `B`, `N`, `F`.

An `EvidenceKernel Welfare` assigns such a profile to each population. The
kernel is deliberately left abstract: later gates must justify whether it is
generated by reasons, observers, models, or some other evidential mechanism.
-/

/-- A rational probability point on the four FDE cells `T/B/N/F`. -/
structure FourCellProbability where
  t : Rat
  b : Rat
  n : Rat
  f : Rat
  t_nonnegative : 0 ≤ t
  b_nonnegative : 0 ≤ b
  n_nonnegative : 0 ≤ n
  f_nonnegative : 0 ≤ f
  normalized : t + b + n + f = 1

namespace FourCellProbability

/-- Total mass supporting the comparison: strict truth plus glut mass. -/
def positive (profile : FourCellProbability) : Rat :=
  profile.t + profile.b

/-- Total mass rejecting the comparison: strict falsity plus glut mass. -/
def negative (profile : FourCellProbability) : Rat :=
  profile.f + profile.b

/-- Threshold a four-cell probability profile using the existing independent
positive/negative 4-PEL support semantics. -/
def thresholdValue (cutoff : Rat)
    (profile : FourCellProbability) : FDEValue :=
  supportThresholdState cutoff profile.positive profile.negative

/-- The classical conflict projection forgets the four-cell decomposition and
records only that both support coordinates clear the threshold. -/
def ClassicalConflict (cutoff : Rat)
    (profile : FourCellProbability) : Prop :=
  cutoff ≤ profile.positive ∧ cutoff ≤ profile.negative

/-- A pure glut profile: all evidence mass lies in cell `B`. -/
def pureB : FourCellProbability :=
  { t := 0, b := 1, n := 0, f := 0
    t_nonnegative := by decide
    b_nonnegative := by decide
    n_nonnegative := by decide
    f_nonnegative := by decide
    normalized := by
      simp only [Rat.zero_add, Rat.add_zero] }

/-- A pure gap profile: all evidence mass lies in cell `N`. -/
def pureN : FourCellProbability :=
  { t := 0, b := 0, n := 1, f := 0
    t_nonnegative := by decide
    b_nonnegative := by decide
    n_nonnegative := by decide
    f_nonnegative := by decide
    normalized := by
      simp only [Rat.zero_add, Rat.add_zero] }

/-- The classical projection sees a contradiction in the pure-`B` profile. -/
theorem pureB_classicalConflict :
    ClassicalConflict 1 pureB := by
  have hPositive : pureB.positive = 1 := by
    simp only [positive, pureB, Rat.zero_add]
  have hNegative : pureB.negative = 1 := by
    simp only [negative, pureB, Rat.zero_add]
  constructor
  · rw [hPositive]
  · rw [hNegative]

/-- The four-valued lift retains the contradiction as `B`. -/
theorem pureB_thresholdValue :
    thresholdValue 1 pureB = FDEValue.B := by
  have hPositive : pureB.positive = 1 := by
    simp only [positive, pureB, Rat.zero_add]
  have hNegative : pureB.negative = 1 := by
    simp only [negative, pureB, Rat.zero_add]
  rw [thresholdValue, hPositive, hNegative]
  rfl

/-- The pure-`N` profile remains a gap at the same threshold. -/
theorem pureN_thresholdValue :
    thresholdValue 1 pureN = FDEValue.N := by
  have hPositive : pureN.positive = 0 := by
    simp only [positive, pureN, Rat.zero_add]
  have hNegative : pureN.negative = 0 := by
    simp only [negative, pureN, Rat.zero_add]
  rw [thresholdValue, hPositive, hNegative]
  rfl

end FourCellProbability

/-- A population-indexed stochastic kernel into the four-cell evidence
simplex. Each output is already a normalized `Delta^3` point. -/
abbrev EvidenceKernel (Welfare : Type) :=
  Population Welfare -> FourCellProbability

/-! ## A finite non-trivial kernel witness -/

inductive KernelWelfare
  | marked
  deriving DecidableEq, Repr

/-- The marked population receives a glut profile; the empty background
receives a gap profile. -/
def finiteWitnessKernel : EvidenceKernel KernelWelfare
  | [] => FourCellProbability.pureN
  | _ => FourCellProbability.pureB

theorem finiteWitnessKernel_target_is_glut :
    FourCellProbability.thresholdValue 1
      (finiteWitnessKernel [KernelWelfare.marked]) = FDEValue.B := by
  exact FourCellProbability.pureB_thresholdValue

theorem finiteWitnessKernel_unrelated_is_gap :
    FourCellProbability.thresholdValue 1
      (finiteWitnessKernel []) = FDEValue.N := by
  exact FourCellProbability.pureN_thresholdValue

/-- The kernel witnesses the precise non-triviality boundary: one population
can project to classical conflict and lift to `B`, while another remains `N`.
No explosion from the first status to the second is licensed. -/
theorem finiteWitnessKernel_conflict_without_triviality :
    FourCellProbability.ClassicalConflict 1
        (finiteWitnessKernel [KernelWelfare.marked]) ∧
      FourCellProbability.thresholdValue 1
        (finiteWitnessKernel [KernelWelfare.marked]) = FDEValue.B ∧
      FourCellProbability.thresholdValue 1
        (finiteWitnessKernel []) = FDEValue.N := by
  exact ⟨FourCellProbability.pureB_classicalConflict,
    finiteWitnessKernel_target_is_glut,
    finiteWitnessKernel_unrelated_is_gap⟩

end PEL4.PopulationAxiology
