import PEL4.PopulationAxiology.RiskyCompensation

namespace PEL4.PopulationAxiology

/-!
# Gate 3: a finite reciprocal-risk instance

This module instantiates the Gate 2 contracts on a four-level ordered welfare
carrier.  It distinguishes two achievements:

1. a generated step relation satisfies the quantifier structure of rational
   Risky General Non-Extreme Priority;
2. two explicit population-prospect steps move lower-outcome probability from
   `0` through `p` to `p+p=1`, and a population evidence kernel lifts that
   endpoint to a non-trivial 4-PEL glut.

The generated step relation is a formal contract instance, not yet a
substantive population axiology.  That boundary prevents the construction from
smuggling the desired comparison into a numerical welfare functional.
-/

/-! ## A small ordered welfare carrier -/

inductive Gate3Welfare
  | lower
  | upper
  | barelyPositive
  | veryPositive
  deriving DecidableEq, Repr

/-- Numerical rank used only to expose the finite order. -/
def Gate3Welfare.rank : Gate3Welfare -> Nat
  | .lower => 0
  | .upper => 1
  | .barelyPositive => 2
  | .veryPositive => 3

def Gate3Welfare.LE (x y : Gate3Welfare) : Prop :=
  x.rank ≤ y.rank

def Gate3Welfare.LT (x y : Gate3Welfare) : Prop :=
  x.rank < y.rank

theorem gate3Welfare_ordered_chain :
    Gate3Welfare.LT .lower .upper ∧
      Gate3Welfare.LT .upper .barelyPositive ∧
      Gate3Welfare.LT .barelyPositive .veryPositive := by
  change 0 < 1 ∧ 1 < 2 ∧ 2 < 3
  decide

theorem gate3Welfare_le_refl : forall x, Gate3Welfare.LE x x := by
  intro x
  exact Nat.le_refl x.rank

theorem gate3Welfare_le_trans : forall {x y z},
    Gate3Welfare.LE x y -> Gate3Welfare.LE y z -> Gate3Welfare.LE x z := by
  intro x y z hxy hyz
  exact Nat.le_trans hxy hyz

theorem gate3Welfare_le_total : forall x y,
    Gate3Welfare.LE x y ∨ Gate3Welfare.LE y x := by
  intro x y
  exact Nat.le_total x.rank y.rank

def gate3Lower (_ : Gate3Welfare) : Gate3Welfare :=
  .lower

def gate3BarelyPositive (w : Gate3Welfare) : Prop :=
  w = .barelyPositive

def gate3VeryPositive (w : Gate3Welfare) : Prop :=
  w = .veryPositive

/-! ## Quantifier-faithful generated RGNEP steps -/

/-- The relation generated by one `m=1` risky compensation move with fixed
increment `p`.  It is intentionally syntactic: substantive axiological
evaluation is deferred to a later gate. -/
def Gate3GeneratedRiskyMove (p : Rat) :
    BinaryProspect (Population Gate3Welfare) ->
    BinaryProspect (Population Gate3Welfare) -> Prop :=
  fun left right =>
    exists a : Gate3Welfare, exists k : Rat,
    exists b c : Gate3Welfare, exists background : Population Gate3Welfare,
      0 ≤ k ∧ k ≤ 1 - p ∧
      gate3BarelyPositive b ∧ gate3VeryPositive c ∧
      BinaryPopulationProspectEquivalent
        (riskShiftProspect background a (gate3Lower a) 1 b k) left ∧
      BinaryPopulationProspectEquivalent
        (riskShiftProspect background a (gate3Lower a) 1 c (k + p)) right ∧
      BinaryProspect.Valid left ∧ BinaryProspect.Valid right

/-- On the finite carrier, the generated move relation satisfies the exact
rational RGNEP quantifier contract whenever `p` is positive and `p=1/2`.
The proof is uniform in `k`, the band witnesses, and the background population.
-/
theorem gate3_generated_rgnep
    (p : Rat)
    (hp : 0 < p)
    (hReciprocal : p = 1 / (2 : Rat)) :
    RationalRiskyGeneralNonExtremePriority
      gate3Lower gate3BarelyPositive gate3VeryPositive
      (Gate3GeneratedRiskyMove p) := by
  intro a
  refine ⟨1, 2, p, by decide, hp, hReciprocal, ?_⟩
  intro k hk0 hkp b c hb hc background
  have hValid := riskShiftProspect_pair_valid
    background a (gate3Lower a) 1 b c k p hk0 hkp (Rat.le_of_lt hp)
  exact ⟨a, k, b, c, background, hk0, hkp, hb, hc,
    binaryPopulationProspectEquivalent_refl _,
    binaryPopulationProspectEquivalent_refl _, hValid.1, hValid.2⟩

/-! ## Two concrete prospect steps -/

/-- A two-compensation-block prospect.  `firstLevel` and `secondLevel`
record which blocks have already been upgraded. -/
def gate3TwoBlockProspect
    (distinguished : Gate3Welfare)
    (firstLevel secondLevel : Gate3Welfare)
    (lowerProbability : Rat) :
    BinaryProspect (Population Gate3Welfare) :=
  { higherOutcome := [distinguished, firstLevel, secondLevel]
    lowerOutcome := [gate3Lower distinguished, firstLevel, secondLevel]
    lowerProbability := lowerProbability }

def gate3StartProspect : BinaryProspect (Population Gate3Welfare) :=
  gate3TwoBlockProspect .upper .barelyPositive .barelyPositive 0

def gate3MiddleProspect (p : Rat) :
    BinaryProspect (Population Gate3Welfare) :=
  gate3TwoBlockProspect .upper .veryPositive .barelyPositive p

def gate3FinishProspect (p : Rat) :
    BinaryProspect (Population Gate3Welfare) :=
  gate3TwoBlockProspect .upper .veryPositive .veryPositive (p + p)

/-- Both non-trivial prospects and the two endpoints are valid whenever
`p≥0` and the two reciprocal increments sum to one. -/
theorem gate3_prospects_valid
    (p : Rat)
    (hp0 : 0 ≤ p)
    (hTotal : p + p = 1) :
    BinaryProspect.Valid gate3StartProspect ∧
      BinaryProspect.Valid (gate3MiddleProspect p) ∧
      BinaryProspect.Valid (gate3FinishProspect p) := by
  have hp1 : p ≤ 1 := by
    have h : p ≤ p + p := by
      have hAdd := (Rat.add_le_add_left (a := 0) (b := p) (c := p)).2 hp0
      simpa only [Rat.add_zero] using hAdd
    simpa only [hTotal] using h
  constructor
  · exact ⟨by decide, by decide⟩
  constructor
  · exact ⟨hp0, hp1⟩
  · change 0 ≤ p + p ∧ p + p ≤ 1
    rw [hTotal]
    exact ⟨by decide, by decide⟩

/-- The first concrete edge is generated by RGNEP with the still-barely-
positive block treated as background. Population permutation is essential:
the list presentations differ although the populations are anonymous. -/
theorem gate3_first_step_generated
    (p : Rat)
    (hp0 : 0 ≤ p)
    (hTotal : p + p = 1) :
    Gate3GeneratedRiskyMove p gate3StartProspect
      (gate3MiddleProspect p) := by
  have hValid := gate3_prospects_valid p hp0 hTotal
  have hp1 : p ≤ 1 := by
    have h : p ≤ p + p := by
      have hAdd := (Rat.add_le_add_left (a := 0) (b := p) (c := p)).2 hp0
      simpa only [Rat.add_zero] using hAdd
    simpa only [hTotal] using h
  have hOneMinusNonnegative : 0 ≤ 1 - p :=
    (Rat.le_iff_sub_nonneg p 1).1 hp1
  refine ⟨.upper, 0, .barelyPositive, .veryPositive,
    [.barelyPositive], by decide, hOneMinusNonnegative,
    rfl, rfl, ?_, ?_, hValid.1, hValid.2.1⟩
  · refine ⟨?_, ?_, rfl⟩
    · exact List.Perm.swap Gate3Welfare.upper Gate3Welfare.barelyPositive
        [Gate3Welfare.barelyPositive]
    · exact List.Perm.swap Gate3Welfare.lower Gate3Welfare.barelyPositive
        [Gate3Welfare.barelyPositive]
  · refine ⟨?_, ?_, Rat.zero_add p⟩
    · exact
        (List.Perm.swap Gate3Welfare.upper Gate3Welfare.barelyPositive
          [Gate3Welfare.veryPositive]).trans
        ((List.Perm.swap Gate3Welfare.veryPositive
          Gate3Welfare.barelyPositive []).cons Gate3Welfare.upper)
    · exact
        (List.Perm.swap Gate3Welfare.lower Gate3Welfare.barelyPositive
          [Gate3Welfare.veryPositive]).trans
        ((List.Perm.swap Gate3Welfare.veryPositive
          Gate3Welfare.barelyPositive []).cons Gate3Welfare.lower)

/-- The second edge is generated by the same increment, now treating the
already-upgraded block as background. -/
theorem gate3_second_step_generated
    (p : Rat)
    (hp0 : 0 ≤ p)
    (hTotal : p + p = 1) :
    Gate3GeneratedRiskyMove p (gate3MiddleProspect p)
      (gate3FinishProspect p) := by
  have hValid := gate3_prospects_valid p hp0 hTotal
  have hp_le_one_minus : p ≤ 1 - p := by
    have hSub : p + (1 - p) = 1 := by
      rw [Rat.add_comm]
      exact Rat.sub_add_cancel
    have hSame : p + (1 - p) = p + p := hSub.trans hTotal.symm
    have hEq : 1 - p = p := Rat.add_left_cancel p hSame
    rw [hEq]
    exact Rat.le_refl
  refine ⟨.upper, p, .barelyPositive, .veryPositive,
    [.veryPositive], hp0, hp_le_one_minus,
    rfl, rfl, ?_, ?_, hValid.2.1, hValid.2.2⟩
  · refine ⟨?_, ?_, rfl⟩
    · exact List.Perm.swap Gate3Welfare.upper Gate3Welfare.veryPositive
        [Gate3Welfare.barelyPositive]
    · exact List.Perm.swap Gate3Welfare.lower Gate3Welfare.veryPositive
        [Gate3Welfare.barelyPositive]
  · refine ⟨?_, ?_, rfl⟩
    · exact List.Perm.swap Gate3Welfare.upper Gate3Welfare.veryPositive
        [Gate3Welfare.veryPositive]
    · exact List.Perm.swap Gate3Welfare.lower Gate3Welfare.veryPositive
        [Gate3Welfare.veryPositive]

/-- The prospects form an exact chain of two identical probability
increments. -/
theorem gate3_exact_two_step_chain
    (p : Rat)
    (hp0 : 0 ≤ p)
    (hTotal : p + p = 1) :
    ExactStepChain (Gate3GeneratedRiskyMove p) 2
      gate3StartProspect (gate3FinishProspect p) := by
  exact ExactStepChain.succ (gate3_first_step_generated p hp0 hTotal)
    (ExactStepChain.succ (gate3_second_step_generated p hp0 hTotal)
      (ExactStepChain.zero _))

/-- Packaging the two prospect steps as a reciprocal-risk chain.  The closing
equation is kept explicit so the theorem is kernel-checked independently of
closed rational normalization. -/
def gate3ReciprocalRiskChain
    (p : Rat)
    (hp : 0 < p)
    (hTotal : p + p = 1)
    (hProduct : (2 : Rat) * p = 1) :
    ReciprocalRiskChain Gate3GeneratedRiskyMove
      gate3StartProspect (gate3FinishProspect p) :=
  { rounds := 2
    increment := p
    rounds_positive := by decide
    increment_positive := hp
    closes_total_risk := hProduct
    steps := gate3_exact_two_step_chain p (Rat.le_of_lt hp) hTotal }

/-! ## Population kernel and evidence lift -/

/-- Populations headed by the lower distinguished welfare level carry pure
glut evidence; all other populations carry pure gap evidence. -/
def gate3PopulationKernel : EvidenceKernel Gate3Welfare
  | .lower :: _ => FourCellProbability.pureB
  | _ => FourCellProbability.pureN

/-- Evidence profile induced by mixing a pure-`N` higher outcome and a pure-`B`
lower outcome with probability `q`. -/
def pureNBMixture
    (q : Rat)
    (hValid : 0 ≤ q ∧ q ≤ 1) : FourCellProbability :=
  { t := 0
    b := q
    n := 1 - q
    f := 0
    t_nonnegative := by decide
    b_nonnegative := hValid.1
    n_nonnegative := (Rat.le_iff_sub_nonneg q 1).1 hValid.2
    f_nonnegative := by decide
    normalized := by
      simp only [Rat.zero_add, Rat.add_zero]
      rw [Rat.add_comm q (1 - q)]
      exact Rat.sub_add_cancel }

/-- The concrete population kernel has the pure-`N`/pure-`B` endpoint shape
for every one of the three two-block prospects. -/
theorem gate3_kernel_endpoint_shape
    (first second : Gate3Welfare) (q : Rat) :
    gate3PopulationKernel
        (gate3TwoBlockProspect .upper first second q).higherOutcome =
          FourCellProbability.pureN ∧
      gate3PopulationKernel
        (gate3TwoBlockProspect .upper first second q).lowerOutcome =
          FourCellProbability.pureB := by
  exact ⟨rfl, rfl⟩

theorem pureNBMixture_zero_is_gap
    (hValid : 0 ≤ (0 : Rat) ∧ (0 : Rat) ≤ 1) :
    FourCellProbability.thresholdValue 1 (pureNBMixture 0 hValid) =
      FDEValue.N := by
  have hPositive : (pureNBMixture 0 hValid).positive = 0 := by
    simp only [FourCellProbability.positive, pureNBMixture, Rat.zero_add]
  have hNegative : (pureNBMixture 0 hValid).negative = 0 := by
    simp only [FourCellProbability.negative, pureNBMixture, Rat.zero_add]
  rw [FourCellProbability.thresholdValue, hPositive, hNegative]
  rfl

theorem pureNBMixture_total_is_glut
    (q : Rat)
    (hValid : 0 ≤ q ∧ q ≤ 1)
    (hq : q = 1) :
    FourCellProbability.thresholdValue 1 (pureNBMixture q hValid) =
      FDEValue.B := by
  have hPositive : (pureNBMixture q hValid).positive = 1 := by
    simp only [FourCellProbability.positive, pureNBMixture, Rat.zero_add, hq]
  have hNegative : (pureNBMixture q hValid).negative = 1 := by
    simp only [FourCellProbability.negative, pureNBMixture, Rat.zero_add, hq]
  rw [FourCellProbability.thresholdValue, hPositive, hNegative]
  rfl

/-- Gate 3's endpoint theorem: the explicit two-step probability path starts
at a gap and ends at a classical conflict whose 4-PEL lift is `B`. -/
theorem gate3_kernel_coupled_endpoint
    (p : Rat)
    (hp0 : 0 ≤ p)
    (hTotal : p + p = 1) :
    FourCellProbability.thresholdValue 1
        (pureNBMixture 0 ⟨by decide, by decide⟩) = FDEValue.N ∧
      FourCellProbability.ClassicalConflict 1
        (pureNBMixture (p + p)
          (gate3_prospects_valid p hp0 hTotal).2.2) ∧
      FourCellProbability.thresholdValue 1
        (pureNBMixture (p + p)
          (gate3_prospects_valid p hp0 hTotal).2.2) = FDEValue.B := by
  have hEndValid := (gate3_prospects_valid p hp0 hTotal).2.2
  have hEndB := pureNBMixture_total_is_glut
    (p + p) hEndValid hTotal
  have hPositive :
      (pureNBMixture (p + p) hEndValid).positive = 1 := by
    simp only [FourCellProbability.positive, pureNBMixture,
      Rat.zero_add, hTotal]
  have hNegative :
      (pureNBMixture (p + p) hEndValid).negative = 1 := by
    simp only [FourCellProbability.negative, pureNBMixture,
      Rat.zero_add, hTotal]
  refine ⟨pureNBMixture_zero_is_gap _, ?_, hEndB⟩
  constructor
  · rw [hPositive]
    exact Rat.le_refl
  · rw [hNegative]
    exact Rat.le_refl

end PEL4.PopulationAxiology
