import PEL4.PopulationAxiology.RiskyCompensationInstance

namespace PEL4.PopulationAxiology

/-!
# Gate 4: a substantive anonymous comparison semantics

Gate 3 used a relation generated by the desired risky-move syntax.  This
module replaces that relation with two independently defined evaluations:

* `Gate4Supports` compares the welfare mass of the designated lower outcome,
  giving a maximin-style safety-floor semantics;
* `Gate4PriorityRejects` detects a strict increase in the probability that the
  distinguished life occupies the lower outcome.

Neither relation mentions `Gate3GeneratedRiskyMove`.  Both are invariant under
permutation equivalence of population prospects.  The safety-floor semantics
satisfies the full rational RGNEP contract, its two concrete local edges
compose to the endpoint, and the independent priority relation rejects that
same endpoint.  Their 4-PEL comparison value is therefore derived as `B`.
-/

/-! ## Anonymous population welfare mass -/

/-- Welfare contribution used by the Gate 4 safety-floor semantics.  The
distinguished upper/lower pair contributes no compensation mass; moving a
life from barely positive to very positive strictly raises the score. -/
def gate4WelfareContribution : Gate3Welfare -> Rat
  | .lower => 0
  | .upper => 0
  | .barelyPositive => 1
  | .veryPositive => 2

/-- Additive population score. Its recursion is later proved invariant under
permutation, so list position carries no evaluative significance. -/
def gate4PopulationScore : Population Gate3Welfare -> Rat
  | [] => 0
  | welfare :: population =>
      gate4WelfareContribution welfare + gate4PopulationScore population

theorem gate4PopulationScore_append
    (left right : Population Gate3Welfare) :
    gate4PopulationScore (left ++ right) =
      gate4PopulationScore left + gate4PopulationScore right := by
  induction left with
  | nil =>
      simp only [List.nil_append, gate4PopulationScore, Rat.zero_add]
  | cons welfare population ih =>
      simp only [List.cons_append, gate4PopulationScore, ih, Rat.add_assoc]

/-- The aggregate score depends on the population multiset, not list order. -/
theorem gate4PopulationScore_perm
    {left right : Population Gate3Welfare}
    (hPerm : List.Perm left right) :
    gate4PopulationScore left = gate4PopulationScore right := by
  induction hPerm with
  | nil => rfl
  | cons welfare _ ih =>
      simp only [gate4PopulationScore, ih]
  | swap first second population =>
      simp only [gate4PopulationScore, Rat.add_assoc,
        Rat.add_comm, Rat.add_left_comm]
  | trans _ _ ihLeft ihRight =>
      exact ihLeft.trans ihRight

/-! ## Two independent prospect judgements -/

/-- Maximin-style value of a binary prospect: evaluate its designated lower
outcome. The probability coordinate remains constrained by prospect validity
but is not traded against the safety floor. -/
def gate4SafetyScore
    (prospect : BinaryProspect (Population Gate3Welfare)) : Rat :=
  gate4PopulationScore prospect.lowerOutcome

/-- Positive comparison evidence: the right prospect has at least as high a
safety floor as the left prospect. -/
def Gate4Supports :
    BinaryProspect (Population Gate3Welfare) ->
    BinaryProspect (Population Gate3Welfare) -> Prop :=
  fun left right => gate4SafetyScore left ≤ gate4SafetyScore right

/-- Negative comparison evidence: the move strictly raises the probability
that the distinguished life occupies its lower welfare state. -/
def Gate4PriorityRejects :
    BinaryProspect (Population Gate3Welfare) ->
    BinaryProspect (Population Gate3Welfare) -> Prop :=
  fun left right => left.lowerProbability < right.lowerProbability

instance gate4Supports_decidable : DecidableRel Gate4Supports := by
  intro left right
  unfold Gate4Supports
  infer_instance

instance gate4PriorityRejects_decidable :
    DecidableRel Gate4PriorityRejects := by
  intro left right
  unfold Gate4PriorityRejects
  infer_instance

theorem gate4Supports_refl : forall prospect, Gate4Supports prospect prospect := by
  intro prospect
  exact Rat.le_refl

theorem gate4Supports_trans : forall {first second third},
    Gate4Supports first second -> Gate4Supports second third ->
      Gate4Supports first third := by
  intro first second third hFirst hSecond
  exact Rat.le_trans hFirst hSecond

theorem gate4SafetyScore_equivalent
    {left right : BinaryProspect (Population Gate3Welfare)}
    (hEquivalent : BinaryPopulationProspectEquivalent left right) :
    gate4SafetyScore left = gate4SafetyScore right :=
  gate4PopulationScore_perm hEquivalent.2.1

/-- Positive comparison is well-defined on anonymous prospect classes. -/
theorem gate4Supports_equivalent
    {left left' right right' :
      BinaryProspect (Population Gate3Welfare)}
    (hLeft : BinaryPopulationProspectEquivalent left left')
    (hRight : BinaryPopulationProspectEquivalent right right') :
    Gate4Supports left right ↔ Gate4Supports left' right' := by
  unfold Gate4Supports
  rw [gate4SafetyScore_equivalent hLeft,
    gate4SafetyScore_equivalent hRight]

/-- Priority rejection is likewise independent of list presentation. -/
theorem gate4PriorityRejects_equivalent
    {left left' right right' :
      BinaryProspect (Population Gate3Welfare)}
    (hLeft : BinaryPopulationProspectEquivalent left left')
    (hRight : BinaryPopulationProspectEquivalent right right') :
    Gate4PriorityRejects left right ↔
      Gate4PriorityRejects left' right' := by
  unfold Gate4PriorityRejects
  rw [hLeft.2.2, hRight.2.2]

/-! ## RGNEP derived from the semantics -/

theorem gate4_riskShift_safety_score
    (background : Population Gate3Welfare)
    (upper compensation : Gate3Welfare)
    (k : Rat) :
    gate4SafetyScore
        (riskShiftProspect background upper (gate3Lower upper) 1
          compensation k) =
      gate4PopulationScore background +
        gate4WelfareContribution compensation := by
  simp only [gate4SafetyScore, riskShiftProspect, addWelfareBlock,
    gate3Lower, gate4PopulationScore_append, List.replicate_succ,
    List.replicate_zero, List.append_nil, gate4PopulationScore,
    gate4WelfareContribution, Rat.add_zero, Rat.zero_add, Rat.add_assoc]

/-- Unlike the generated Gate 3 relation, the comparison relation here is
fixed in advance. Its safety-floor ordering proves the complete quantifier
contract of rational RGNEP on the four-level carrier. -/
theorem gate4_semantic_rgnep :
    RationalRiskyGeneralNonExtremePriority
      gate3Lower gate3BarelyPositive gate3VeryPositive Gate4Supports := by
  intro upper
  refine ⟨1, 2, 1 / (2 : Rat), by decide, by decide, rfl, ?_⟩
  intro k _ _ barely very hBarely hVery background
  rcases hBarely with rfl
  rcases hVery with rfl
  unfold Gate4Supports
  rw [gate4_riskShift_safety_score,
    gate4_riskShift_safety_score]
  exact (Rat.add_le_add_left (a := (1 : Rat)) (b := 2)
    (c := gate4PopulationScore background)).2 (by decide)

/-! ## Concrete semantic chain and independent rejection -/

theorem gate4_start_safety_score :
    gate4SafetyScore gate3StartProspect = 2 := by
  rfl

theorem gate4_middle_safety_score (p : Rat) :
    gate4SafetyScore (gate3MiddleProspect p) = 3 := by
  rfl

theorem gate4_finish_safety_score (p : Rat) :
    gate4SafetyScore (gate3FinishProspect p) = 4 := by
  rfl

theorem gate4_first_step_supported (p : Rat) :
    Gate4Supports gate3StartProspect (gate3MiddleProspect p) := by
  unfold Gate4Supports
  rw [gate4_start_safety_score, gate4_middle_safety_score]
  decide

theorem gate4_second_step_supported (p : Rat) :
    Gate4Supports (gate3MiddleProspect p) (gate3FinishProspect p) := by
  unfold Gate4Supports
  rw [gate4_middle_safety_score, gate4_finish_safety_score]
  decide

/-- Gate 3's syntactic edges and Gate 4's independently evaluated edges agree
on both concrete risk steps. -/
theorem gate4_generated_and_supported_steps
    (p : Rat)
    (hp0 : 0 ≤ p)
    (hTotal : p + p = 1) :
    (Gate3GeneratedRiskyMove p gate3StartProspect
        (gate3MiddleProspect p) ∧
      Gate4Supports gate3StartProspect (gate3MiddleProspect p)) ∧
    (Gate3GeneratedRiskyMove p (gate3MiddleProspect p)
        (gate3FinishProspect p) ∧
      Gate4Supports (gate3MiddleProspect p) (gate3FinishProspect p)) := by
  exact ⟨⟨gate3_first_step_generated p hp0 hTotal,
      gate4_first_step_supported p⟩,
    ⟨gate3_second_step_generated p hp0 hTotal,
      gate4_second_step_supported p⟩⟩

theorem gate4_exact_semantic_chain (p : Rat) :
    ExactStepChain Gate4Supports 2 gate3StartProspect
      (gate3FinishProspect p) := by
  exact ExactStepChain.succ (gate4_first_step_supported p)
    (ExactStepChain.succ (gate4_second_step_supported p)
      (ExactStepChain.zero _))

/-- Endpoint support is transported through the independently defined
safety-floor order. -/
theorem gate4_endpoint_supported (p : Rat) :
    Gate4Supports gate3StartProspect (gate3FinishProspect p) := by
  exact (gate4_exact_semantic_chain p).transport
    gate4Supports_refl gate4Supports_trans (fun h => h)

/-- The priority route is independent of the aggregate safety-floor score: it
sees the accumulated lower-state probability, which reaches certainty. -/
theorem gate4_endpoint_priority_rejected
    (p : Rat)
    (hTotal : p + p = 1) :
    Gate4PriorityRejects gate3StartProspect (gate3FinishProspect p) := by
  unfold Gate4PriorityRejects gate3StartProspect gate3FinishProspect
    gate3TwoBlockProspect
  rw [hTotal]
  decide

/-- Gate 4's central result: the glut is derived from two independent
substantive judgements, rather than encoded in a generated comparison. -/
theorem gate4_substantive_endpoint_is_glut
    (p : Rat)
    (hTotal : p + p = 1) :
    comparisonValue Gate4Supports Gate4PriorityRejects
      gate3StartProspect (gate3FinishProspect p) = FDEValue.B := by
  exact comparisonValue_eq_B Gate4Supports Gate4PriorityRejects
    (gate4_endpoint_supported p)
    (gate4_endpoint_priority_rejected p hTotal)

/-- Non-explosion remains explicit: the reverse comparison is neither
supported by the safety-floor order nor rejected by the priority relation. -/
theorem gate4_reverse_comparison_is_gap
    (p : Rat)
    (hTotal : p + p = 1) :
    comparisonValue Gate4Supports Gate4PriorityRejects
      (gate3FinishProspect p) gate3StartProspect = FDEValue.N := by
  have hNotSupported :
      ¬ Gate4Supports (gate3FinishProspect p) gate3StartProspect := by
    unfold Gate4Supports
    rw [gate4_finish_safety_score, gate4_start_safety_score]
    decide
  have hNotRejected :
      ¬ Gate4PriorityRejects (gate3FinishProspect p)
        gate3StartProspect := by
    unfold Gate4PriorityRejects gate3StartProspect gate3FinishProspect
      gate3TwoBlockProspect
    rw [hTotal]
    decide
  simp [comparisonValue, hNotSupported, hNotRejected, FDEValue.N]

end PEL4.PopulationAxiology
