import PEL4.PosteriorSampleComplexity

namespace PEL4

/-!
# Gate 75: discounted Bellman fixed-point witness

Gate 69 used a finite horizon. Gate 75 isolates the discounted fixed-point idea
in a deliberately small executable witness, without importing an external
algebra tactic stack.

The operator is `T(v) = 1 + v/2`. Lean verifies the candidate fixed point `2`,
its first value-iteration approximants, and exact residual halving through the
first four iterations. This is a machine-checked contraction witness, not yet a
general Banach fixed-point theorem.
-/

/-- Minimal discounted Bellman operator with immediate reward one and discount
factor one half. -/
def gate75Bellman (value : Rat) : Rat := 1 + value / 2

/-- Candidate infinite-horizon value. -/
def gate75FixedPoint : Rat := 2

/-- Finite approximants generated by repeated Bellman updates from zero. -/
def gate75ValueIteration : Nat -> Rat
  | 0 => 0
  | n + 1 => gate75Bellman (gate75ValueIteration n)

/-- Residual distance below the candidate fixed point. -/
def gate75Residual (n : Nat) : Rat :=
  gate75FixedPoint - gate75ValueIteration n

/-- The candidate is exactly a fixed point. -/
theorem gate75_fixed_point :
    gate75Bellman gate75FixedPoint = gate75FixedPoint := by
  native_decide

/-- A concrete Bellman difference witnesses the factor-one-half contraction. -/
theorem gate75_difference_halves :
    gate75Bellman (gate75ValueIteration 1) -
        gate75Bellman (gate75ValueIteration 0) =
      (gate75ValueIteration 1 - gate75ValueIteration 0) / 2 := by
  native_decide

/-- Exact residuals in the verified iteration window. -/
theorem gate75_residual_window :
    gate75Residual 0 = 2 ∧
    gate75Residual 1 = 1 ∧
    gate75Residual 2 = (1 : Rat) / 2 ∧
    gate75Residual 3 = (1 : Rat) / 4 ∧
    gate75Residual 4 = (1 : Rat) / 8 := by
  native_decide

/-- In the verified window every Bellman iteration halves the residual. -/
theorem gate75_residual_halves :
    gate75Residual 1 = gate75Residual 0 / 2 ∧
    gate75Residual 2 = gate75Residual 1 / 2 ∧
    gate75Residual 3 = gate75Residual 2 / 2 ∧
    gate75Residual 4 = gate75Residual 3 / 2 := by
  native_decide

/-- Among the explicit approximation ladder plus the candidate endpoint, only
`2` is a Bellman fixed point. -/
theorem gate75_fixed_point_unique :
    ([0, 1, (3 : Rat) / 2, (7 : Rat) / 4, (15 : Rat) / 8, 2].filter
      (fun value => gate75Bellman value = value)) = [2] := by
  native_decide

/-- First exact approximants: `0, 1, 3/2, 7/4, 15/8`. -/
theorem gate75_first_approximants :
    gate75ValueIteration 0 = 0 ∧
    gate75ValueIteration 1 = 1 ∧
    gate75ValueIteration 2 = (3 : Rat) / 2 ∧
    gate75ValueIteration 3 = (7 : Rat) / 4 ∧
    gate75ValueIteration 4 = (15 : Rat) / 8 := by
  native_decide

/-- The iteration-level contraction statement for the entire verified window. -/
theorem gate75_iteration_residual_halves :
    gate75Residual 1 = gate75Residual 0 / 2 ∧
    gate75Residual 2 = gate75Residual 1 / 2 ∧
    gate75Residual 3 = gate75Residual 2 / 2 ∧
    gate75Residual 4 = gate75Residual 3 / 2 :=
  gate75_residual_halves

/-- Main Gate-75 result: a discounted Bellman witness has a checked fixed point
and a geometric error pattern across the verified value-iteration window. -/
theorem gate75_discounted_bellman_fixed_point :
    gate75Bellman gate75FixedPoint = gate75FixedPoint ∧
    gate75Residual 0 = 2 ∧
    gate75Residual 1 = 1 ∧
    gate75Residual 2 = (1 : Rat) / 2 ∧
    gate75Residual 3 = (1 : Rat) / 4 ∧
    gate75Residual 4 = (1 : Rat) / 8 := by
  exact ⟨gate75_fixed_point,
    gate75_residual_window.1,
    gate75_residual_window.2.1,
    gate75_residual_window.2.2.1,
    gate75_residual_window.2.2.2.1,
    gate75_residual_window.2.2.2.2⟩

/-!
## Gate-75 boundary

This gate is intentionally a finite executable contraction witness. It does not
yet prove uniqueness over all rationals, convergence for all iteration counts,
or a complete infinite-horizon 4PEL belief MDP. Those stronger statements need
a dedicated ordered/algebraic library layer rather than hidden tactic imports.
-/

end PEL4
