import PEL4.CompositionalClassicalRecovery
import PEL4.ModalDynamicsRobustness
import PEL4.ModalDynamicsBeliefRestoration

namespace PEL4

/-!
# Gate 11: dynamic compositional recovery

Gate 10 isolates a recursive contract under which full modal formulas evaluate
classically. This module begins Gate 11 by asking when that contract survives
an admissible probability-only conditionalization.

Since `conditionalize` preserves valuations, accessibility, and thresholds,
the only new obligations are the threshold-completeness clauses generated by
reachable `bel` nodes. The predicate below records exactly those posterior
obligations along the same local syntax/accessibility recursion as Gate 10.
-/

/-- Posterior threshold-completeness obligations encountered from `phi` at
`w`. Propositional and non-probabilistic modal nodes add no new obligation;
every reachable belief node must be complete in the conditionalized model. -/
def ModalFormula.PostUpdateBeliefCompleteAt
    {W Ag Atom : Type} [DecidableEq W]
    (m : Model W Ag Atom) (E : Formula Atom Ag)
    (hAdm : ConditionalizationAdmissible m E) :
    W → ModalFormula Atom Ag → Prop
  | _, ModalFormula.prop _ => True
  | w, ModalFormula.not phi =>
      ModalFormula.PostUpdateBeliefCompleteAt m E hAdm w phi
  | w, ModalFormula.and phi psi =>
      ModalFormula.PostUpdateBeliefCompleteAt m E hAdm w phi ∧
      ModalFormula.PostUpdateBeliefCompleteAt m E hAdm w psi
  | w, ModalFormula.bel i phi =>
      (∀ u, u ∈ m.R i w →
        ModalFormula.PostUpdateBeliefCompleteAt m E hAdm u phi) ∧
      BeliefThresholdComplete (conditionalize m E hAdm) i w
        (fun u => evalModal (conditionalize m E hAdm) u phi)
  | w, ModalFormula.know i phi =>
      ∀ u, u ∈ m.R i w →
        ModalFormula.PostUpdateBeliefCompleteAt m E hAdm u phi
  | w, ModalFormula.poss i phi =>
      ∀ u, u ∈ m.R i w →
        ModalFormula.PostUpdateBeliefCompleteAt m E hAdm u phi

/-- Exact local Gate-11 boundary: once a formula is recovered before an
admissible update, recovery afterwards is equivalent to all posterior belief
nodes encountered by the recursive contract remaining threshold-complete. -/
theorem compositionalRecoveryAt_conditionalize_iff_postUpdateBeliefCompleteAt
    {W Ag Atom : Type} [DecidableEq W]
    (m : Model W Ag Atom) (E : Formula Atom Ag)
    (hAdm : ConditionalizationAdmissible m E)
    (phi : ModalFormula Atom Ag) :
    ∀ w,
      ModalFormula.CompositionalRecoveryAt m w phi →
      (ModalFormula.CompositionalRecoveryAt
          (conditionalize m E hAdm) w phi ↔
        ModalFormula.PostUpdateBeliefCompleteAt m E hAdm w phi) := by
  induction phi with
  | prop p =>
      intro w hBefore
      constructor
      · intro _
        trivial
      · intro _
        exact hBefore
  | not phi ih =>
      intro w hBefore
      exact ih w hBefore
  | and phi psi ihPhi ihPsi =>
      intro w hBefore
      constructor
      · intro hAfter
        exact
          ⟨(ihPhi w hBefore.1).1 hAfter.1,
            (ihPsi w hBefore.2).1 hAfter.2⟩
      · intro hPost
        exact
          ⟨(ihPhi w hBefore.1).2 hPost.1,
            (ihPsi w hBefore.2).2 hPost.2⟩
  | bel i phi ih =>
      intro w hBefore
      constructor
      · intro hAfter
        exact
          ⟨fun u hu => (ih u (hBefore.1 u hu)).1 (hAfter.1 u hu),
            hAfter.2⟩
      · intro hPost
        exact
          ⟨fun u hu => (ih u (hBefore.1 u hu)).2 (hPost.1 u hu),
            hPost.2⟩
  | know i phi ih =>
      intro w hBefore
      constructor
      · intro hAfter u hu
        exact (ih u (hBefore u hu)).1 (hAfter u hu)
      · intro hPost u hu
        exact (ih u (hBefore u hu)).2 (hPost u hu)
  | poss i phi ih =>
      intro w hBefore
      constructor
      · intro hAfter u hu
        exact (ih u (hBefore u hu)).1 (hAfter u hu)
      · intro hPost u hu
        exact (ih u (hBefore u hu)).2 (hPost u hu)

/-- Global collection of all locally reachable posterior belief-completeness
obligations. -/
def ModalFormula.PostUpdateBeliefComplete
    {W Ag Atom : Type} [DecidableEq W]
    (m : Model W Ag Atom) (E : Formula Atom Ag)
    (hAdm : ConditionalizationAdmissible m E)
    (phi : ModalFormula Atom Ag) : Prop :=
  ∀ w, ModalFormula.PostUpdateBeliefCompleteAt m E hAdm w phi

/-- Global exact preservation criterion for Gate-10 recovery. -/
theorem compositionalRecovery_conditionalize_iff_postUpdateBeliefComplete
    {W Ag Atom : Type} [DecidableEq W]
    (m : Model W Ag Atom) (E : Formula Atom Ag)
    (hAdm : ConditionalizationAdmissible m E)
    (phi : ModalFormula Atom Ag)
    (hBefore : ModalFormula.CompositionalRecovery m phi) :
    ModalFormula.CompositionalRecovery (conditionalize m E hAdm) phi ↔
      ModalFormula.PostUpdateBeliefComplete m E hAdm phi := by
  constructor
  · intro hAfter w
    exact
      (compositionalRecoveryAt_conditionalize_iff_postUpdateBeliefCompleteAt
        m E hAdm phi w (hBefore w)).1 (hAfter w)
  · intro hPost w
    exact
      (compositionalRecoveryAt_conditionalize_iff_postUpdateBeliefCompleteAt
        m E hAdm phi w (hBefore w)).2 (hPost w)

/-! ## Value and consequence preservation under threshold robustness -/

/-- Gate-10 recovery plus threshold-side robustness preserves classical
evaluation even when the stronger recursive recovery contract is not assumed
for the posterior model. -/
theorem evalModal_conditionalize_isClassical_of_recovery_and_robust
    {W Ag Atom : Type} [DecidableEq W]
    (m : Model W Ag Atom)
    (hIntegrity : ModelProbabilityIntegrity m)
    (E : Formula Atom Ag)
    (hAdm : ConditionalizationAdmissible m E)
    (phi : ModalFormula Atom Ag)
    (hRecovery : ModalFormula.CompositionalRecovery m phi)
    (hRobust : ModalConditionalizationRobust m E hAdm phi) :
    ∀ w, IsClassicalValue (evalModal (conditionalize m E hAdm) w phi) := by
  intro w
  rw [evalModal_conditionalize_of_robust m E hAdm hRobust w]
  exact evalModal_isClassical_of_global_compositionalRecovery
    m hIntegrity phi hRecovery w

/-- A robust update preserves the Gate-10 ST/LP collapse for a recovered
antecedent, without requiring the consequent to be recovered. -/
theorem modalST_iff_LP_after_conditionalize_of_recovery_and_robust
    {W Ag Atom : Type} [DecidableEq W]
    (m : Model W Ag Atom)
    (hIntegrity : ModelProbabilityIntegrity m)
    (E : Formula Atom Ag)
    (hAdm : ConditionalizationAdmissible m E)
    (phi psi : ModalFormula Atom Ag)
    (hRecovery : ModalFormula.CompositionalRecovery m phi)
    (hRobust : ModalConditionalizationRobust m E hAdm phi) :
    ModalST_SemanticEntailsIn (conditionalize m E hAdm) phi psi ↔
      ModalLP_SemanticEntailsIn (conditionalize m E hAdm) phi psi := by
  have hClassical :=
    evalModal_conditionalize_isClassical_of_recovery_and_robust
      m hIntegrity E hAdm phi hRecovery hRobust
  constructor
  · intro hST w hPos
    apply hST w
    rcases hClassical w with hT | hF
    · exact hT
    · rw [hF] at hPos
      contradiction
  · exact ModalLP_SemanticEntailsIn_implies_ST
      (conditionalize m E hAdm) phi psi

/-! ## Two-sided finite boundary -/

/-- A strict-true belief value witnesses that at least its positive threshold
bit fires. -/
theorem beliefThresholdComplete_of_evalModal_bel_eq_T
    {W Ag Atom : Type} [DecidableEq W]
    (m : Model W Ag Atom) (i : Ag) (w : W)
    (phi : ModalFormula Atom Ag)
    (hT : evalModal m w (ModalFormula.bel i phi) = FDEValue.T) :
    BeliefThresholdComplete m i w (fun u => evalModal m u phi) := by
  have hBits := belief_eq_thresholdBits m i w
    (fun u => evalModal m u phi)
  have hStruct :
      { pos := beliefPositiveThresholdBit m i w
          (fun u => evalModal m u phi)
      , neg := beliefNegativeThresholdBit m i w
          (fun u => evalModal m u phi) } = FDEValue.T := by
    exact hBits.symm.trans hT
  have hPos :
      beliefPositiveThresholdBit m i w
        (fun u => evalModal m u phi) = true := by
    simpa [FDEValue.T] using congrArg FDEValue.pos hStruct
  exact Or.inl hPos

/-- A gappy belief value witnesses failure of threshold completeness. -/
theorem not_beliefThresholdComplete_of_evalModal_bel_eq_N
    {W Ag Atom : Type} [DecidableEq W]
    (m : Model W Ag Atom) (i : Ag) (w : W)
    (phi : ModalFormula Atom Ag)
    (hN : evalModal m w (ModalFormula.bel i phi) = FDEValue.N) :
    ¬ BeliefThresholdComplete m i w (fun u => evalModal m u phi) := by
  have hBits := belief_eq_thresholdBits m i w
    (fun u => evalModal m u phi)
  have hStruct :
      { pos := beliefPositiveThresholdBit m i w
          (fun u => evalModal m u phi)
      , neg := beliefNegativeThresholdBit m i w
          (fun u => evalModal m u phi) } = FDEValue.N := by
    exact hBits.symm.trans hN
  have hPos :
      beliefPositiveThresholdBit m i w
        (fun u => evalModal m u phi) = false := by
    simpa [FDEValue.N] using congrArg FDEValue.pos hStruct
  have hNeg :
      beliefNegativeThresholdBit m i w
        (fun u => evalModal m u phi) = false := by
    simpa [FDEValue.N] using congrArg FDEValue.neg hStruct
  unfold BeliefThresholdComplete
  simp [hPos, hNeg]

/-- In the instability model, `B p` satisfies the recursive recovery contract
before conditioning. -/
theorem dynamic_instability_belP_recovered_before :
    ModalFormula.CompositionalRecovery
      DynamicInstabilityModel dynamicInstabilityBelP := by
  intro w
  constructor
  · intro u _
    cases u
    · exact Or.inl rfl
    · exact Or.inr rfl
    · exact Or.inl rfl
  · rcases dynamic_instability_belief_profile_before with ⟨ha, hb, hc⟩
    cases w
    · exact beliefThresholdComplete_of_evalModal_bel_eq_T
        DynamicInstabilityModel DynamicInstabilityAgent.i
        DynamicInstabilityWorld.a dynamicInstabilityP ha
    · exact beliefThresholdComplete_of_evalModal_bel_eq_T
        DynamicInstabilityModel DynamicInstabilityAgent.i
        DynamicInstabilityWorld.b dynamicInstabilityP hb
    · exact beliefThresholdComplete_of_evalModal_bel_eq_T
        DynamicInstabilityModel DynamicInstabilityAgent.i
        DynamicInstabilityWorld.c dynamicInstabilityP hc

/-- The same admissible update destroys recovery because `B p = N` at `b`. -/
theorem dynamic_instability_belP_not_recovered_after :
    ¬ ModalFormula.CompositionalRecovery
      DynamicInstabilityUpdated dynamicInstabilityBelP := by
  intro hRecovery
  have hIncomplete :
      ¬ BeliefThresholdComplete DynamicInstabilityUpdated
        DynamicInstabilityAgent.i DynamicInstabilityWorld.b
        (fun u => evalModal DynamicInstabilityUpdated u dynamicInstabilityP) := by
    exact not_beliefThresholdComplete_of_evalModal_bel_eq_N
      DynamicInstabilityUpdated DynamicInstabilityAgent.i
      DynamicInstabilityWorld.b dynamicInstabilityP
      dynamic_instability_belief_profile_after.2.1
  exact hIncomplete (hRecovery DynamicInstabilityWorld.b).2

/-- In the restoration model, the prior gap at `b` prevents recovery. -/
theorem dynamic_restoration_belP_not_recovered_before :
    ¬ ModalFormula.CompositionalRecovery
      DynamicRestorationModel dynamicInstabilityBelP := by
  intro hRecovery
  have hIncomplete :
      ¬ BeliefThresholdComplete DynamicRestorationModel
        DynamicInstabilityAgent.i DynamicInstabilityWorld.b
        (fun u => evalModal DynamicRestorationModel u dynamicInstabilityP) := by
    exact not_beliefThresholdComplete_of_evalModal_bel_eq_N
      DynamicRestorationModel DynamicInstabilityAgent.i
      DynamicInstabilityWorld.b dynamicInstabilityP
      dynamic_restoration_belief_profile_before.2.1
  exact hIncomplete (hRecovery DynamicInstabilityWorld.b).2

/-- Conditioning on `p` restores threshold completeness and hence the full
recursive recovery contract for `B p`. -/
theorem dynamic_restoration_belP_recovered_after :
    ModalFormula.CompositionalRecovery
      DynamicRestorationUpdated dynamicInstabilityBelP := by
  intro w
  constructor
  · intro u _
    cases u
    · exact Or.inl rfl
    · exact Or.inr rfl
    · exact Or.inl rfl
  · rcases dynamic_restoration_belief_profile_after with ⟨ha, hb, hc⟩
    cases w
    · exact beliefThresholdComplete_of_evalModal_bel_eq_T
        DynamicRestorationUpdated DynamicInstabilityAgent.i
        DynamicInstabilityWorld.a dynamicInstabilityP ha
    · exact beliefThresholdComplete_of_evalModal_bel_eq_T
        DynamicRestorationUpdated DynamicInstabilityAgent.i
        DynamicInstabilityWorld.b dynamicInstabilityP hb
    · exact beliefThresholdComplete_of_evalModal_bel_eq_T
        DynamicRestorationUpdated DynamicInstabilityAgent.i
        DynamicInstabilityWorld.c dynamicInstabilityP hc

/-- Admissible conditionalization can therefore move compositional recovery in
both directions. -/
theorem conditionalization_recovery_is_not_monotone :
    (ModalFormula.CompositionalRecovery
        DynamicInstabilityModel dynamicInstabilityBelP ∧
      ¬ ModalFormula.CompositionalRecovery
        DynamicInstabilityUpdated dynamicInstabilityBelP) ∧
    (¬ ModalFormula.CompositionalRecovery
        DynamicRestorationModel dynamicInstabilityBelP ∧
      ModalFormula.CompositionalRecovery
        DynamicRestorationUpdated dynamicInstabilityBelP) := by
  exact
    ⟨⟨dynamic_instability_belP_recovered_before,
        dynamic_instability_belP_not_recovered_after⟩,
      ⟨dynamic_restoration_belP_not_recovered_before,
        dynamic_restoration_belP_recovered_after⟩⟩

end PEL4
