import PEL4.EpistemicPathDependence
import PEL4.ConditionalizationAtomicIdempotence

namespace PEL4

/-!
# Gate 29: concrete asymptotic epistemic path dependence

The abstract Gate-29 witness already showed that one recovered start state can
have valid futures with different eventual Recovery endpoints.  The concrete
one-step split then showed the same branching phenomenon inside the existing
`DynamicInstabilityModel` under two admissible atomic pieces of evidence.

This module closes the remaining gap.  Repeating either atomic evidence after
its first update is an idempotent conditionalization stutter, so both concrete
branches extend to genuine infinite update schedules.  One is recovered from
step one onward; the other is non-recovered from step one onward.
-/

/-- An infinite trajectory is generated by repeated conditionalization on the
same atomic proposition when every successor is obtained by an admissible
conditioning on that atom. -/
def RepeatedAtomicConditionalizationFollows
    {W Ag Atom : Type} [DecidableEq W]
    (p : Atom) (trajectory : Nat → Model W Ag Atom) : Prop :=
  ∀ n,
    ∃ hAdm : ConditionalizationAdmissible
        (trajectory n) (Formula.prop p),
      trajectory (n + 1) =
        conditionalize (trajectory n) (Formula.prop p) hAdm

/-- Concrete Recovery branch: learn `p` once, then repeat the same evidence
forever.  Idempotence makes the posterior model constant from index one. -/
def gate29ConcreteRecoveryTrajectory :
    Nat → Model DynamicInstabilityWorld DynamicInstabilityAgent DynamicInstabilityAtom
  | 0 => DynamicInstabilityModel
  | _ + 1 => Gate29RecoveryPreservingUpdated

/-- Concrete Non-Recovery branch: learn `e` once, then repeat that same evidence
forever.  The first update destroys Recovery and all later repetitions stutter. -/
def gate29ConcreteNonRecoveryTrajectory :
    Nat → Model DynamicInstabilityWorld DynamicInstabilityAgent DynamicInstabilityAtom
  | 0 => DynamicInstabilityModel
  | _ + 1 => DynamicInstabilityUpdated

@[simp] theorem gate29_concreteRecovery_starts_at_common_model :
    gate29ConcreteRecoveryTrajectory 0 = DynamicInstabilityModel := rfl

@[simp] theorem gate29_concreteNonRecovery_starts_at_common_model :
    gate29ConcreteNonRecoveryTrajectory 0 = DynamicInstabilityModel := rfl

/-- The `p` branch is a genuine infinite schedule of admissible atomic
conditionalizations. -/
theorem gate29_concreteRecovery_repeatedConditionalization :
    RepeatedAtomicConditionalizationFollows
      DynamicInstabilityAtom.p gate29ConcreteRecoveryTrajectory := by
  intro n
  cases n with
  | zero =>
      refine ⟨gate29_recoveryPreservingEvidence_admissible, ?_⟩
      rfl
  | succ k =>
      let hRepeat := conditionalize_prop_repeat_admissible
        DynamicInstabilityModel DynamicInstabilityAtom.p
        gate29_recoveryPreservingEvidence_admissible
      refine ⟨hRepeat, ?_⟩
      have hIdem := conditionalize_repeat_prop_eq
        DynamicInstabilityModel DynamicInstabilityAtom.p
        gate29_recoveryPreservingEvidence_admissible hRepeat
      simpa [gate29ConcreteRecoveryTrajectory,
        Gate29RecoveryPreservingUpdated, gate29RecoveryPreservingEvidence] using
        hIdem.symm

/-- The `e` branch is likewise a genuine infinite schedule of admissible atomic
conditionalizations. -/
theorem gate29_concreteNonRecovery_repeatedConditionalization :
    RepeatedAtomicConditionalizationFollows
      DynamicInstabilityAtom.e gate29ConcreteNonRecoveryTrajectory := by
  intro n
  cases n with
  | zero =>
      refine ⟨dynamic_instability_evidence_admissible, ?_⟩
      rfl
  | succ k =>
      let hRepeat := conditionalize_prop_repeat_admissible
        DynamicInstabilityModel DynamicInstabilityAtom.e
        dynamic_instability_evidence_admissible
      refine ⟨hRepeat, ?_⟩
      have hIdem := conditionalize_repeat_prop_eq
        DynamicInstabilityModel DynamicInstabilityAtom.e
        dynamic_instability_evidence_admissible hRepeat
      simpa [gate29ConcreteNonRecoveryTrajectory,
        DynamicInstabilityUpdated, dynamicInstabilityEvidence] using hIdem.symm

/-- Recovery is permanent on the first concrete branch from the first update
onward. -/
theorem gate29_concreteRecovery_eventually_recovered :
    ∃ N, ∀ n, N ≤ n →
      ModalFormula.CompositionalRecovery
        (gate29ConcreteRecoveryTrajectory n) dynamicInstabilityBelP := by
  refine ⟨1, ?_⟩
  intro n hn
  cases n with
  | zero => omega
  | succ k =>
      exact gate29_recoveryPreserving_update_recovered

/-- Non-Recovery is permanent on the second concrete branch from the first
update onward. -/
theorem gate29_concreteNonRecovery_eventually_nonRecovered :
    ∃ N, ∀ n, N ≤ n →
      ¬ ModalFormula.CompositionalRecovery
        (gate29ConcreteNonRecoveryTrajectory n) dynamicInstabilityBelP := by
  refine ⟨1, ?_⟩
  intro n hn
  cases n with
  | zero => omega
  | succ k =>
      exact dynamic_instability_belP_not_recovered_after

/-- The concrete branches are already distinct after the first update. -/
theorem gate29_concrete_paths_diverge_after_first_update :
    gate29ConcreteRecoveryTrajectory 1 ≠
      gate29ConcreteNonRecoveryTrajectory 1 := by
  intro hModels
  have hRecovered :
      ModalFormula.CompositionalRecovery
        (gate29ConcreteRecoveryTrajectory 1) dynamicInstabilityBelP := by
    simpa [gate29ConcreteRecoveryTrajectory] using
      gate29_recoveryPreserving_update_recovered
  have hNotRecovered :
      ¬ ModalFormula.CompositionalRecovery
        (gate29ConcreteNonRecoveryTrajectory 1) dynamicInstabilityBelP := by
    simpa [gate29ConcreteNonRecoveryTrajectory] using
      dynamic_instability_belP_not_recovered_after
  rw [hModels] at hRecovered
  exact hNotRecovered hRecovered

/-- Main concrete Gate-29 result: from one identical 4PEL model, two admissible
infinite atomic-evidence schedules have different permanent Recovery phases.
The split occurs at the first update and each branch then becomes an idempotent
conditionalization fixed point. -/
theorem gate29_concrete_asymptotic_path_dependence :
    gate29ConcreteRecoveryTrajectory 0 = DynamicInstabilityModel ∧
    gate29ConcreteNonRecoveryTrajectory 0 = DynamicInstabilityModel ∧
    RepeatedAtomicConditionalizationFollows
      DynamicInstabilityAtom.p gate29ConcreteRecoveryTrajectory ∧
    RepeatedAtomicConditionalizationFollows
      DynamicInstabilityAtom.e gate29ConcreteNonRecoveryTrajectory ∧
    (∃ N, ∀ n, N ≤ n →
      ModalFormula.CompositionalRecovery
        (gate29ConcreteRecoveryTrajectory n) dynamicInstabilityBelP) ∧
    (∃ N, ∀ n, N ≤ n →
      ¬ ModalFormula.CompositionalRecovery
        (gate29ConcreteNonRecoveryTrajectory n) dynamicInstabilityBelP) := by
  exact ⟨rfl, rfl,
    gate29_concreteRecovery_repeatedConditionalization,
    gate29_concreteNonRecovery_repeatedConditionalization,
    gate29_concreteRecovery_eventually_recovered,
    gate29_concreteNonRecovery_eventually_nonRecovered⟩

end PEL4
