import PEL4.Evidence

namespace PEL4

/-!
# Matroidal evidence at the coarse 4-PEL channel level

This file adds a deliberately lightweight closure presentation of a matroid.
It does not assume that arbitrary bodies of evidence form matroids. Instead it
constructs the canonical two-channel partition structure induced by the 4-PEL
positive/negative evidence split.

At this coarse level, two evidence atoms with the same polarity are parallel:
once one representative of a polarity is present, further atoms of that same
polarity lie in its closure. Positive and negative atoms remain distinct
information channels.
-/

universe u

/-- Predicate presentation of a set, avoiding any external set library. -/
abbrev EvidenceSet (α : Type u) := α → Prop

namespace EvidenceSet

/-- Inclusion between predicate-presented sets. -/
def Subset {α : Type u} (A B : EvidenceSet α) : Prop :=
  ∀ ⦃x⦄, A x → B x

/-- Insert one element into a predicate-presented set. -/
def insert {α : Type u} (x : α) (A : EvidenceSet α) : EvidenceSet α :=
  fun y => y = x ∨ A y

/-- Singleton predicate-presented set. -/
def singleton {α : Type u} (x : α) : EvidenceSet α :=
  fun y => y = x

end EvidenceSet

/--
A closure-operator presentation of the matroid axioms used in this development.
Idempotence is stored in the nontrivial direction; the reverse direction follows
from extensivity applied to `cl A`.
-/
structure MatroidClosure (α : Type u) where
  cl : EvidenceSet α → EvidenceSet α
  extensive : ∀ A, EvidenceSet.Subset A (cl A)
  monotone : ∀ {A B}, EvidenceSet.Subset A B → EvidenceSet.Subset (cl A) (cl B)
  idempotent : ∀ A, EvidenceSet.Subset (cl (cl A)) (cl A)
  exchange : ∀ {A} {x y : α},
    cl (EvidenceSet.insert y A) x →
    ¬ cl A x →
    cl (EvidenceSet.insert x A) y

/-- The two primitive 4-PEL evidence directions. -/
inductive EvidencePolarity where
  | positive
  | negative
  deriving DecidableEq, Repr

/--
Coarse channel closure: an evidence atom is generated by `A` exactly when `A`
contains an atom of the same polarity.
-/
def channelClosure {α : Type u}
    (polarity : α → EvidencePolarity)
    (A : EvidenceSet α) : EvidenceSet α :=
  fun e => ∃ a, A a ∧ polarity a = polarity e

/--
The positive/negative channel closure satisfies the matroid closure axioms.
This is the canonical rank-at-most-two partition matroid behind the coarse
4-PEL evidence signature.
-/
def channelMatroid {α : Type u}
    (polarity : α → EvidencePolarity) : MatroidClosure α where
  cl := channelClosure polarity
  extensive := by
    intro A x hx
    exact ⟨x, hx, rfl⟩
  monotone := by
    intro A B hAB x hx
    cases hx with
    | intro a ha =>
        exact ⟨a, hAB ha.1, ha.2⟩
  idempotent := by
    intro A x hx
    cases hx with
    | intro a ha =>
        cases ha.1 with
        | intro b hb =>
            exact ⟨b, hb.1, Eq.trans hb.2 ha.2⟩
  exchange := by
    intro A x y hxy hx
    cases hxy with
    | intro a ha =>
        cases ha.1 with
        | inl hay =>
            have hpxy : polarity x = polarity y :=
              Eq.trans (Eq.symm ha.2) (congrArg polarity hay)
            exact ⟨x, Or.inl rfl, hpxy⟩
        | inr hAa =>
            exact False.elim (hx ⟨a, hAa, ha.2⟩)

/-- Two atoms are parallel at the coarse level exactly when they share polarity. -/
theorem samePolarity_iff_mem_singletonClosure {α : Type u}
    (polarity : α → EvidencePolarity) (x y : α) :
    channelClosure polarity (EvidenceSet.singleton x) y ↔
      polarity x = polarity y := by
  constructor
  · intro h
    cases h with
    | intro a ha =>
        exact Eq.trans (Eq.symm (congrArg polarity ha.1)) ha.2
  · intro h
    exact ⟨x, rfl, h⟩

/-- Presence of one of the two evidence channels in a body of evidence. -/
def supportsChannel {α : Type u}
    (polarity : α → EvidencePolarity)
    (A : EvidenceSet α)
    (channel : EvidencePolarity) : Prop :=
  ∃ e, A e ∧ polarity e = channel

/-- Coarse channel closure adds no new positive or negative support channel. -/
theorem supportsChannel_channelClosure_iff {α : Type u}
    (polarity : α → EvidencePolarity)
    (A : EvidenceSet α)
    (channel : EvidencePolarity) :
    supportsChannel polarity (channelClosure polarity A) channel ↔
      supportsChannel polarity A channel := by
  constructor
  · intro h
    cases h with
    | intro e he =>
        cases he.1 with
        | intro a ha =>
            exact ⟨a, ha.1, Eq.trans ha.2 he.2⟩
  · intro h
    cases h with
    | intro e he =>
        exact ⟨e, ⟨e, he.1, rfl⟩, he.2⟩

/--
A body of evidence realizes a four-valued state when the state's Boolean bits
exactly track presence of positive and negative evidence channels.
-/
def RealizesFDE {α : Type u}
    (polarity : α → EvidencePolarity)
    (A : EvidenceSet α)
    (v : FDEValue) : Prop :=
  (v.pos = true ↔ supportsChannel polarity A EvidencePolarity.positive) ∧
  (v.neg = true ↔ supportsChannel polarity A EvidencePolarity.negative)

/-- Matroidal channel closure is conservative for the coarse four-valued state. -/
theorem realizesFDE_channelClosure_iff {α : Type u}
    (polarity : α → EvidencePolarity)
    (A : EvidenceSet α)
    (v : FDEValue) :
    RealizesFDE polarity (channelClosure polarity A) v ↔
      RealizesFDE polarity A v := by
  constructor
  · intro h
    constructor
    · constructor
      · intro hv
        exact (supportsChannel_channelClosure_iff polarity A EvidencePolarity.positive).1 (h.1.1 hv)
      · intro hs
        exact h.1.2 ((supportsChannel_channelClosure_iff polarity A EvidencePolarity.positive).2 hs)
    · constructor
      · intro hv
        exact (supportsChannel_channelClosure_iff polarity A EvidencePolarity.negative).1 (h.2.1 hv)
      · intro hs
        exact h.2.2 ((supportsChannel_channelClosure_iff polarity A EvidencePolarity.negative).2 hs)
  · intro h
    constructor
    · constructor
      · intro hv
        exact (supportsChannel_channelClosure_iff polarity A EvidencePolarity.positive).2 (h.1.1 hv)
      · intro hs
        exact h.1.2 ((supportsChannel_channelClosure_iff polarity A EvidencePolarity.positive).1 hs)
    · constructor
      · intro hv
        exact (supportsChannel_channelClosure_iff polarity A EvidencePolarity.negative).2 (h.2.1 hv)
      · intro hs
        exact h.2.2 ((supportsChannel_channelClosure_iff polarity A EvidencePolarity.negative).1 hs)

/-- The glut value is realized exactly when both independent channels occur. -/
theorem realizesFDE_B_iff {α : Type u}
    (polarity : α → EvidencePolarity)
    (A : EvidenceSet α) :
    RealizesFDE polarity A FDEValue.B ↔
      supportsChannel polarity A EvidencePolarity.positive ∧
      supportsChannel polarity A EvidencePolarity.negative := by
  constructor
  · intro h
    exact ⟨h.1.1 rfl, h.2.1 rfl⟩
  · intro h
    constructor
    · constructor
      · intro _
        exact h.1
      · intro _
        rfl
    · constructor
      · intro _
        exact h.2
      · intro _
        rfl

/-- Rank of the coarse two-channel signature encoded by an FDE value. -/
def FDEValue.channelRank (v : FDEValue) : Nat :=
  (if v.pos then 1 else 0) + (if v.neg then 1 else 0)

theorem channelRank_N : FDEValue.channelRank FDEValue.N = 0 := rfl
theorem channelRank_T : FDEValue.channelRank FDEValue.T = 1 := rfl
theorem channelRank_F : FDEValue.channelRank FDEValue.F = 1 := rfl
theorem channelRank_B : FDEValue.channelRank FDEValue.B = 2 := rfl

end PEL4
