import PEL4.MatroidEvidence

namespace PEL4

/-!
# Gate 3: circuits as minimal evidential redundancy

Gate 1 identified the coarse positive/negative evidence split with a rank-at-most-two
partition matroid. Gate 3 asks for its minimal dependent sets. Rather than claiming
that arbitrary epistemic dependence is matroidal, this file remains at the same
coarse channel projection.

A set is channel-dependent exactly when it contains two distinct atoms of the same
polarity. A channel circuit is a dependent set with no smaller dependent subset.
The main characterization proves that every such circuit is exactly a two-element
same-polarity pair.
-/

universe u

namespace EvidenceSet

/-- Empty predicate-presented set. -/
def empty {α : Type u} : EvidenceSet α :=
  fun _ => False

/-- Remove one element from a predicate-presented set. -/
def erase {α : Type u} (x : α) (A : EvidenceSet α) : EvidenceSet α :=
  fun y => A y ∧ y ≠ x

/-- Two-element predicate-presented set. -/
def pair {α : Type u} (x y : α) : EvidenceSet α :=
  fun z => z = x ∨ z = y

end EvidenceSet

/--
Coarse dependence: `A` contains two distinct atoms that occupy the same
positive/negative channel.
-/
def ChannelDependent {α : Type u}
    (polarity : α → EvidencePolarity)
    (A : EvidenceSet α) : Prop :=
  ∃ x y, A x ∧ A y ∧ x ≠ y ∧ polarity x = polarity y

/-- Coarse independence is the absence of a same-polarity duplicate. -/
def ChannelIndependent {α : Type u}
    (polarity : α → EvidencePolarity)
    (A : EvidenceSet α) : Prop :=
  ¬ ChannelDependent polarity A

/--
A channel circuit is a minimally dependent evidence set. Minimality is expressed
order-theoretically: every dependent subset of the circuit already contains the
whole circuit.
-/
def ChannelCircuit {α : Type u}
    (polarity : α → EvidencePolarity)
    (C : EvidenceSet α) : Prop :=
  ChannelDependent polarity C ∧
  ∀ {D : EvidenceSet α},
    EvidenceSet.Subset D C →
    ChannelDependent polarity D →
    EvidenceSet.Subset C D

/--
Closure-theoretic dependence agrees with the duplicate-channel definition: a set
is dependent iff one of its members is generated by the remainder after removing
itself.
-/
theorem channelDependent_iff_mem_closure_erase
    {α : Type u}
    (polarity : α → EvidencePolarity)
    (A : EvidenceSet α) :
    ChannelDependent polarity A ↔
      ∃ x, A x ∧ channelClosure polarity (EvidenceSet.erase x A) x := by
  constructor
  · intro h
    cases h with
    | intro x hrest =>
        cases hrest with
        | intro y hxy =>
            exact ⟨x, hxy.1, ⟨y, ⟨hxy.2.1, by
              intro hyx
              exact hxy.2.2.1 hyx.symm⟩, hxy.2.2.2.symm⟩⟩
  · intro h
    cases h with
    | intro x hx =>
        cases hx.2 with
        | intro y hy =>
            exact ⟨x, y, hx.1, hy.1.1, by
              intro hxy
              exact hy.1.2 hxy.symm, hy.2.symm⟩

/-- A distinct same-polarity pair is a minimal dependent set, and only such pairs are. -/
theorem channelPair_isCircuit_iff
    {α : Type u}
    (polarity : α → EvidencePolarity)
    (x y : α) :
    ChannelCircuit polarity (EvidenceSet.pair x y) ↔
      x ≠ y ∧ polarity x = polarity y := by
  constructor
  · intro h
    cases h.1 with
    | intro a hrest =>
        cases hrest with
        | intro b hab =>
            have haPair := hab.1
            have hbPair := hab.2.1
            cases haPair with
            | inl hax =>
                cases hbPair with
                | inl hbx =>
                    exact False.elim (hab.2.2.1 (hax.trans hbx.symm))
                | inr hby =>
                    subst a
                    subst b
                    exact ⟨hab.2.2.1, hab.2.2.2⟩
            | inr hay =>
                cases hbPair with
                | inl hbx =>
                    subst a
                    subst b
                    exact ⟨by
                      intro hxy
                      exact hab.2.2.1 hxy.symm, hab.2.2.2.symm⟩
                | inr hby =>
                    exact False.elim (hab.2.2.1 (hay.trans hby.symm))
  · intro hxy
    constructor
    · exact ⟨x, y, Or.inl rfl, Or.inr rfl, hxy.1, hxy.2⟩
    · intro D hDC hDdep
      cases hDdep with
      | intro a hrest =>
          cases hrest with
          | intro b hab =>
              have haPair := hDC hab.1
              have hbPair := hDC hab.2.1
              have hDx : D x := by
                cases haPair with
                | inl hax =>
                    simpa [hax] using hab.1
                | inr hay =>
                    cases hbPair with
                    | inl hbx =>
                        simpa [hbx] using hab.2.1
                    | inr hby =>
                        exact False.elim (hab.2.2.1 (hay.trans hby.symm))
              have hDy : D y := by
                cases haPair with
                | inl hax =>
                    cases hbPair with
                    | inl hbx =>
                        exact False.elim (hab.2.2.1 (hax.trans hbx.symm))
                    | inr hby =>
                        simpa [hby] using hab.2.1
                | inr hay =>
                    simpa [hay] using hab.1
              intro z hz
              cases hz with
              | inl hzx =>
                  simpa [hzx] using hDx
              | inr hzy =>
                  simpa [hzy] using hDy

/--
Complete Gate-3 circuit classification: every minimal coarse dependence is exactly
a two-element same-polarity pair.
-/
theorem channelCircuit_iff_exists_samePolarity_pair
    {α : Type u}
    (polarity : α → EvidencePolarity)
    (C : EvidenceSet α) :
    ChannelCircuit polarity C ↔
      ∃ x y,
        x ≠ y ∧
        polarity x = polarity y ∧
        ∀ z, C z ↔ EvidenceSet.pair x y z := by
  constructor
  · intro hC
    cases hC.1 with
    | intro x hrest =>
        cases hrest with
        | intro y hxy =>
            have hPairDep : ChannelDependent polarity (EvidenceSet.pair x y) :=
              ⟨x, y, Or.inl rfl, Or.inr rfl, hxy.2.2.1, hxy.2.2.2⟩
            have hPairSub : EvidenceSet.Subset (EvidenceSet.pair x y) C := by
              intro z hz
              cases hz with
              | inl hzx =>
                  simpa [hzx] using hxy.1
              | inr hzy =>
                  simpa [hzy] using hxy.2.1
            have hCSub : EvidenceSet.Subset C (EvidenceSet.pair x y) :=
              hC.2 hPairSub hPairDep
            exact ⟨x, y, hxy.2.2.1, hxy.2.2.2, fun z =>
              ⟨fun hz => hCSub hz, fun hz => hPairSub hz⟩⟩
  · intro h
    cases h with
    | intro x hrest =>
        cases hrest with
        | intro y hdata =>
            have hPairCircuit : ChannelCircuit polarity (EvidenceSet.pair x y) :=
              (channelPair_isCircuit_iff polarity x y).2 ⟨hdata.1, hdata.2.1⟩
            constructor
            · exact ⟨x, y,
                (hdata.2.2 x).2 (Or.inl rfl),
                (hdata.2.2 y).2 (Or.inr rfl),
                hdata.1,
                hdata.2.1⟩
            · intro D hDC hDdep
              have hDPair : EvidenceSet.Subset D (EvidenceSet.pair x y) := by
                intro z hz
                exact (hdata.2.2 z).1 (hDC hz)
              have hPairD : EvidenceSet.Subset (EvidenceSet.pair x y) D :=
                hPairCircuit.2 hDPair hDdep
              intro z hz
              exact hPairD ((hdata.2.2 z).1 hz)

/--
A same-polarity circuit is pure redundancy at the coarse closure level: retaining
one member generates exactly the same channel closure as retaining the pair.
-/
theorem channelClosure_pair_iff_singleton_of_samePolarity
    {α : Type u}
    (polarity : α → EvidencePolarity)
    {x y : α}
    (hxy : polarity x = polarity y)
    (e : α) :
    channelClosure polarity (EvidenceSet.pair x y) e ↔
      channelClosure polarity (EvidenceSet.singleton x) e := by
  constructor
  · intro h
    cases h with
    | intro a ha =>
        cases ha.1 with
        | inl hax =>
            subst a
            exact ⟨x, rfl, ha.2⟩
        | inr hay =>
            subst a
            exact ⟨x, rfl, Eq.trans hxy ha.2⟩
  · intro h
    cases h with
    | intro a ha =>
        have hax : a = x := ha.1
        subst a
        exact ⟨x, Or.inl rfl, ha.2⟩

/--
Circuit elimination in the two-channel case: two pair-circuits sharing `x`
force the pair of their remaining distinct members to be a circuit.
-/
theorem channelPair_circuit_elimination
    {α : Type u}
    (polarity : α → EvidencePolarity)
    {x y z : α}
    (hXY : ChannelCircuit polarity (EvidenceSet.pair x y))
    (hXZ : ChannelCircuit polarity (EvidenceSet.pair x z))
    (hyz : y ≠ z) :
    ChannelCircuit polarity (EvidenceSet.pair y z) := by
  have hXYData := (channelPair_isCircuit_iff polarity x y).1 hXY
  have hXZData := (channelPair_isCircuit_iff polarity x z).1 hXZ
  apply (channelPair_isCircuit_iff polarity y z).2
  exact ⟨hyz, Eq.trans hXYData.2.symm hXZData.2⟩

/--
Contraction-style background closure: treat `c` as already accepted evidence before
closing a new body `A`. This is not yet packaged as a full minor because the
lightweight `MatroidClosure` interface has no explicit ground set.
-/
def channelClosureWithBackground {α : Type u}
    (polarity : α → EvidencePolarity)
    (c : α)
    (A : EvidenceSet α) : EvidenceSet α :=
  channelClosure polarity (EvidenceSet.insert c A)

/-- Contracting/accepting `c` makes every parallel atom loop-like over empty new evidence. -/
theorem background_generates_samePolarity
    {α : Type u}
    (polarity : α → EvidencePolarity)
    (c e : α)
    (hce : polarity c = polarity e) :
    channelClosureWithBackground polarity c EvidenceSet.empty e := by
  exact ⟨c, Or.inl rfl, hce⟩

/-- Opposite-polarity atoms are not generated by a single accepted background atom. -/
theorem background_does_not_generate_oppositePolarity
    {α : Type u}
    (polarity : α → EvidencePolarity)
    (c e : α)
    (hce : polarity c ≠ polarity e) :
    ¬ channelClosureWithBackground polarity c EvidenceSet.empty e := by
  intro h
  cases h with
  | intro a ha =>
      cases ha.1 with
      | inl hac =>
          subst a
          exact hce ha.2
      | inr hEmpty =>
          exact False.elim hEmpty

end PEL4
