import PEL4.GeneralIdentifiability

namespace PEL4

/-!
# Gate 115: minimal target-separating experiment families

Gate 114 showed that truth-guaranteeing decoding requires only target constancy on
observation fibers; full hidden-world identification is stronger than necessary.
Gate 115 turns that distinction into an explicit experiment-design witness.

Four hidden worlds are observed through two binary experiments. Worlds `a` and `b`
share the same target verdict `T` and remain observationally aliased even after
both experiments. World `c` requires `F`, and world `d` requires `B`. Neither
experiment alone is target-separating, but the pair is. Thus the two-experiment
family is inclusion-minimal for the requested 4PEL target while still failing to
identify the hidden world itself.
-/

inductive Gate115World where
  | a
  | b
  | c
  | d
  deriving DecidableEq, Repr

inductive Gate115Experiment where
  | first
  | second
  deriving DecidableEq, Repr

/-- The target task deliberately identifies `a` and `b` at the verdict level. -/
def gate115Target : Gate115World → FDEValue
  | .a => FDEValue.T
  | .b => FDEValue.T
  | .c => FDEValue.F
  | .d => FDEValue.B

/-- Binary outcomes for the two available experiments. -/
def gate115Observe : Gate115Experiment → Gate115World → Bool
  | .first, .a => false
  | .first, .b => false
  | .first, .c => true
  | .first, .d => false
  | .second, .a => false
  | .second, .b => false
  | .second, .c => false
  | .second, .d => true

/-- Observation trace generated by an experiment family. -/
def gate115Trace (experiments : List Gate115Experiment)
    (world : Gate115World) : List Bool :=
  experiments.map (fun experiment => gate115Observe experiment world)

/-- An experiment family is sufficient for the target task exactly when worlds
that remain observationally aliased have the same target verdict. -/
def Gate115TargetSeparating (experiments : List Gate115Experiment) : Prop :=
  Gate114FiberConsistent (gate115Trace experiments) gate115Target

/-- Full world identification is deliberately stronger: equal traces must imply
that the hidden worlds themselves are equal. -/
def Gate115WorldIdentifying (experiments : List Gate115Experiment) : Prop :=
  ∀ left right : Gate115World,
    gate115Trace experiments left = gate115Trace experiments right →
      left = right

/-- A direct decoder for the two-experiment trace. -/
def gate115PairDecode : List Bool → FDEValue
  | [false, false] => FDEValue.T
  | [true, false] => FDEValue.F
  | [false, true] => FDEValue.B
  | _ => FDEValue.N

/-- The two-experiment family is truth-guaranteeing for the requested target. -/
theorem gate115_pair_decoder_truth_guaranteeing :
    Gate114TruthGuaranteeing
      (gate115Trace [.first, .second]) gate115Target gate115PairDecode := by
  intro world
  cases world <;> rfl

/-- Hence the pair satisfies Gate 114's target-aware fiber criterion. -/
theorem gate115_pair_target_separating :
    Gate115TargetSeparating [.first, .second] := by
  exact gate114_decoder_implies_fiber_consistent
    (gate115Trace [.first, .second]) gate115Target gate115PairDecode
    gate115_pair_decoder_truth_guaranteeing

/-- The first experiment alone aliases `a : T` with `d : B`, so it is not enough
for the target task. -/
theorem gate115_first_not_target_separating :
    ¬ Gate115TargetSeparating [.first] := by
  intro hSeparate
  have hTargets := hSeparate Gate115World.a Gate115World.d (by rfl)
  have hDifferent : gate115Target Gate115World.a ≠ gate115Target Gate115World.d := by
    native_decide
  exact hDifferent hTargets

/-- The second experiment alone aliases `a : T` with `c : F`. -/
theorem gate115_second_not_target_separating :
    ¬ Gate115TargetSeparating [.second] := by
  intro hSeparate
  have hTargets := hSeparate Gate115World.a Gate115World.c (by rfl)
  have hDifferent : gate115Target Gate115World.a ≠ gate115Target Gate115World.c := by
    native_decide
  exact hDifferent hTargets

/-- With no experiment at all, target-different worlds are of course aliased. -/
theorem gate115_empty_not_target_separating :
    ¬ Gate115TargetSeparating [] := by
  intro hSeparate
  have hTargets := hSeparate Gate115World.a Gate115World.c (by rfl)
  have hDifferent : gate115Target Gate115World.a ≠ gate115Target Gate115World.c := by
    native_decide
  exact hDifferent hTargets

/-- Crucially, the sufficient pair is still not a hidden-world identifier: `a`
and `b` produce the same two-bit trace. -/
theorem gate115_pair_not_world_identifying :
    ¬ Gate115WorldIdentifying [.first, .second] := by
  intro hIdentify
  have hEq : Gate115World.a = Gate115World.b :=
    hIdentify Gate115World.a Gate115World.b (by rfl)
  have hNe : Gate115World.a ≠ Gate115World.b := by
    native_decide
  exact hNe hEq

/-- The remaining hidden-world alias is harmless for this task because `a` and
`b` require the same target verdict. -/
theorem gate115_remaining_alias_is_target_harmless :
    gate115Trace [.first, .second] Gate115World.a =
        gate115Trace [.first, .second] Gate115World.b ∧
      gate115Target Gate115World.a = gate115Target Gate115World.b := by
  exact ⟨rfl, rfl⟩

/-- Gate 114 applies uniformly to every experiment family in this witness. -/
theorem gate115_decoder_exists_iff_target_separating
    (experiments : List Gate115Experiment) :
    (∃ decode : List Bool → FDEValue,
      Gate114TruthGuaranteeing
        (gate115Trace experiments) gate115Target decode) ↔
      Gate115TargetSeparating experiments := by
  letI : Inhabited FDEValue := ⟨FDEValue.N⟩
  exact gate114_truth_guaranteeing_decoder_iff_fiber_consistent
    (gate115Trace experiments) gate115Target

/-- Main Gate-115 result: the pair is sufficient, each one-experiment subfamily
(and the empty family) is insufficient, yet the pair intentionally leaves a
same-target hidden-world alias unresolved. This is target-minimal experiment
design rather than full-state reconstruction. -/
theorem gate115_minimal_target_experiment_family :
    Gate115TargetSeparating [.first, .second] ∧
    ¬ Gate115TargetSeparating [.first] ∧
    ¬ Gate115TargetSeparating [.second] ∧
    ¬ Gate115TargetSeparating [] ∧
    ¬ Gate115WorldIdentifying [.first, .second] ∧
    gate115Target Gate115World.a = gate115Target Gate115World.b := by
  exact ⟨gate115_pair_target_separating,
    gate115_first_not_target_separating,
    gate115_second_not_target_separating,
    gate115_empty_not_target_separating,
    gate115_pair_not_world_identifying,
    rfl⟩

/-!
## Gate-115 interpretation boundary

This finite witness proves inclusion-minimality only inside the explicit menu
`{first, second}`. It does not solve a general minimum-cost experiment-set problem.
Nor does it claim that leaving hidden states aliased is always harmless: the alias
is acceptable here precisely because Gate 114's target-aware criterion proves that
all worlds in the remaining fiber require the same verdict.

The conceptual gain over full-state identifiability is task sensitivity. An agent
need not reconstruct every detail of reality before acting correctly on a given
question; it needs only enough experiments to separate worlds whose required
answers differ.
-/

end PEL4
