import PEL4.ModalDynamicsGeometry

namespace PEL4

/-!
# Numerical threshold crossing behind the Boolean square

`ModalDynamicsGeometry` treats the four FDE statuses as vertices of a Boolean
threshold square.  This module reconnects those categorical walls to the
underlying rational support masses.

For one threshold coordinate, endpoint decisions differ exactly when the two
support masses lie on opposite sides of the Lockean threshold:

```text
side_c(x) != side_c(y)
iff
(x < c <= y) or (y < c <= x).
```

This is an order-theoretic endpoint result.  It does not yet introduce a
continuous path or invoke an intermediate-value theorem.  A future continuous
layer can use this straddling theorem as its boundary condition.
-/

/-- Two rational support masses straddle threshold `c` when one lies strictly
below it and the other lies on or above it. -/
def ThresholdStraddles (c x y : Rat) : Prop :=
  (x < c ∧ c ≤ y) ∨ (y < c ∧ c ≤ x)

/-- Exact numerical meaning of a changed Lockean threshold decision. -/
theorem threshold_decision_ne_iff_straddles (c x y : Rat) :
    decide (c ≤ x) ≠ decide (c ≤ y) ↔ ThresholdStraddles c x y := by
  by_cases hx : c ≤ x
  · by_cases hy : c ≤ y
    · have hnx : ¬ x < c := not_lt_of_ge hx
      have hny : ¬ y < c := not_lt_of_ge hy
      simp [ThresholdStraddles, hx, hy, hnx, hny]
    · have hylt : y < c := lt_of_not_ge hy
      have hnx : ¬ x < c := not_lt_of_ge hx
      simp [ThresholdStraddles, hx, hy, hylt, hnx]
  · have hxlt : x < c := lt_of_not_ge hx
    by_cases hy : c ≤ y
    · have hny : ¬ y < c := not_lt_of_ge hy
      simp [ThresholdStraddles, hx, hy, hxlt, hny]
    · have hylt : y < c := lt_of_not_ge hy
      simp [ThresholdStraddles, hx, hy, hxlt, hylt]

/-- One-dimensional categorical displacement generated by two rational support
masses relative to a common threshold. -/
def thresholdDecisionWallCount (c x y : Rat) : Nat :=
  if decide (c ≤ x) = decide (c ≤ y) then 0 else 1

/-- A one-dimensional wall count is one exactly when the masses straddle the
threshold. -/
theorem thresholdDecisionWallCount_eq_one_iff_straddles (c x y : Rat) :
    thresholdDecisionWallCount c x y = 1 ↔ ThresholdStraddles c x y := by
  by_cases hEq : decide (c ≤ x) = decide (c ≤ y)
  · have hNot : ¬ ThresholdStraddles c x y := by
      intro hStraddle
      exact ((threshold_decision_ne_iff_straddles c x y).2 hStraddle) hEq
    simp [thresholdDecisionWallCount, hEq, hNot]
  · have hStraddle : ThresholdStraddles c x y :=
      (threshold_decision_ne_iff_straddles c x y).1 hEq
    simp [thresholdDecisionWallCount, hEq, hStraddle]

/-- A one-dimensional wall count is zero exactly when no threshold straddling
occurs. -/
theorem thresholdDecisionWallCount_eq_zero_iff_not_straddles (c x y : Rat) :
    thresholdDecisionWallCount c x y = 0 ↔ ¬ ThresholdStraddles c x y := by
  by_cases hEq : decide (c ≤ x) = decide (c ≤ y)
  · have hNot : ¬ ThresholdStraddles c x y := by
      intro hStraddle
      exact ((threshold_decision_ne_iff_straddles c x y).2 hStraddle) hEq
    simp [thresholdDecisionWallCount, hEq, hNot]
  · have hStraddle : ThresholdStraddles c x y :=
      (threshold_decision_ne_iff_straddles c x y).1 hEq
    simp [thresholdDecisionWallCount, hEq, hStraddle]

/-- Positive support masses before and after one admissible conditionalization
straddle the agent's fixed threshold. -/
def ConditionalizedPositiveStraddles
    {W Ag Atom : Type} [DecidableEq W]
    (m : Model W Ag Atom) (E : Formula Atom Ag)
    (hAdm : ConditionalizationAdmissible m E)
    (i : Ag) (w : W) (phi : ModalFormula Atom Ag) : Prop :=
  ThresholdStraddles (m.c i)
    (modalPositiveBeliefMass m i w phi)
    (modalPositiveBeliefMass (conditionalize m E hAdm) i w phi)

/-- Negative support analogue of `ConditionalizedPositiveStraddles`. -/
def ConditionalizedNegativeStraddles
    {W Ag Atom : Type} [DecidableEq W]
    (m : Model W Ag Atom) (E : Formula Atom Ag)
    (hAdm : ConditionalizationAdmissible m E)
    (i : Ag) (w : W) (phi : ModalFormula Atom Ag) : Prop :=
  ThresholdStraddles (m.c i)
    (modalNegativeBeliefMass m i w phi)
    (modalNegativeBeliefMass (conditionalize m E hAdm) i w phi)

/-- The Boolean-square displacement of a belief transition is exactly the sum
of the positive and negative one-dimensional threshold-wall counts. -/
theorem conditionalization_belief_wallCount_eq_supportWallCount
    {W Ag Atom : Type} [DecidableEq W]
    (m : Model W Ag Atom) (E : Formula Atom Ag)
    (hAdm : ConditionalizationAdmissible m E)
    (i : Ag) (w : W) (phi : ModalFormula Atom Ag) :
    thresholdWallCount
        (evalModal m w (ModalFormula.bel i phi))
        (evalModal (conditionalize m E hAdm) w (ModalFormula.bel i phi)) =
      thresholdDecisionWallCount (m.c i)
        (modalPositiveBeliefMass m i w phi)
        (modalPositiveBeliefMass (conditionalize m E hAdm) i w phi) +
      thresholdDecisionWallCount (m.c i)
        (modalNegativeBeliefMass m i w phi)
        (modalNegativeBeliefMass (conditionalize m E hAdm) i w phi) := by
  rw [evalModal_bel_eq_threshold_pair m i w phi,
      evalModal_bel_eq_threshold_pair (conditionalize m E hAdm) i w phi]
  rfl

/-- Zero categorical displacement means neither support coordinate straddles
the threshold. -/
theorem conditionalization_belief_zero_walls_iff_no_support_straddles
    {W Ag Atom : Type} [DecidableEq W]
    (m : Model W Ag Atom) (E : Formula Atom Ag)
    (hAdm : ConditionalizationAdmissible m E)
    (i : Ag) (w : W) (phi : ModalFormula Atom Ag) :
    thresholdWallCount
        (evalModal m w (ModalFormula.bel i phi))
        (evalModal (conditionalize m E hAdm) w (ModalFormula.bel i phi)) = 0 ↔
      ¬ ConditionalizedPositiveStraddles m E hAdm i w phi ∧
      ¬ ConditionalizedNegativeStraddles m E hAdm i w phi := by
  rw [conditionalization_belief_wallCount_eq_supportWallCount]
  unfold ConditionalizedPositiveStraddles ConditionalizedNegativeStraddles
  by_cases hp : ThresholdStraddles (m.c i)
      (modalPositiveBeliefMass m i w phi)
      (modalPositiveBeliefMass (conditionalize m E hAdm) i w phi)
  · have hp1 := (thresholdDecisionWallCount_eq_one_iff_straddles
      (m.c i)
      (modalPositiveBeliefMass m i w phi)
      (modalPositiveBeliefMass (conditionalize m E hAdm) i w phi)).2 hp
    by_cases hn : ThresholdStraddles (m.c i)
        (modalNegativeBeliefMass m i w phi)
        (modalNegativeBeliefMass (conditionalize m E hAdm) i w phi)
    · have hn1 := (thresholdDecisionWallCount_eq_one_iff_straddles
        (m.c i)
        (modalNegativeBeliefMass m i w phi)
        (modalNegativeBeliefMass (conditionalize m E hAdm) i w phi)).2 hn
      simp [hp, hn, hp1, hn1]
    · have hn0 := (thresholdDecisionWallCount_eq_zero_iff_not_straddles
        (m.c i)
        (modalNegativeBeliefMass m i w phi)
        (modalNegativeBeliefMass (conditionalize m E hAdm) i w phi)).2 hn
      simp [hp, hn, hp1, hn0]
  · have hp0 := (thresholdDecisionWallCount_eq_zero_iff_not_straddles
      (m.c i)
      (modalPositiveBeliefMass m i w phi)
      (modalPositiveBeliefMass (conditionalize m E hAdm) i w phi)).2 hp
    by_cases hn : ThresholdStraddles (m.c i)
        (modalNegativeBeliefMass m i w phi)
        (modalNegativeBeliefMass (conditionalize m E hAdm) i w phi)
    · have hn1 := (thresholdDecisionWallCount_eq_one_iff_straddles
        (m.c i)
        (modalNegativeBeliefMass m i w phi)
        (modalNegativeBeliefMass (conditionalize m E hAdm) i w phi)).2 hn
      simp [hp, hn, hp0, hn1]
    · have hn0 := (thresholdDecisionWallCount_eq_zero_iff_not_straddles
        (m.c i)
        (modalNegativeBeliefMass m i w phi)
        (modalNegativeBeliefMass (conditionalize m E hAdm) i w phi)).2 hn
      simp [hp, hn, hp0, hn0]

/-- One wall means exactly one of the positive and negative support coordinates
straddles threshold. -/
theorem conditionalization_belief_one_wall_iff_exactly_one_support_straddles
    {W Ag Atom : Type} [DecidableEq W]
    (m : Model W Ag Atom) (E : Formula Atom Ag)
    (hAdm : ConditionalizationAdmissible m E)
    (i : Ag) (w : W) (phi : ModalFormula Atom Ag) :
    thresholdWallCount
        (evalModal m w (ModalFormula.bel i phi))
        (evalModal (conditionalize m E hAdm) w (ModalFormula.bel i phi)) = 1 ↔
      (ConditionalizedPositiveStraddles m E hAdm i w phi ∧
        ¬ ConditionalizedNegativeStraddles m E hAdm i w phi) ∨
      (¬ ConditionalizedPositiveStraddles m E hAdm i w phi ∧
        ConditionalizedNegativeStraddles m E hAdm i w phi) := by
  rw [conditionalization_belief_wallCount_eq_supportWallCount]
  unfold ConditionalizedPositiveStraddles ConditionalizedNegativeStraddles
  by_cases hp : ThresholdStraddles (m.c i)
      (modalPositiveBeliefMass m i w phi)
      (modalPositiveBeliefMass (conditionalize m E hAdm) i w phi)
  · have hp1 := (thresholdDecisionWallCount_eq_one_iff_straddles
      (m.c i)
      (modalPositiveBeliefMass m i w phi)
      (modalPositiveBeliefMass (conditionalize m E hAdm) i w phi)).2 hp
    by_cases hn : ThresholdStraddles (m.c i)
        (modalNegativeBeliefMass m i w phi)
        (modalNegativeBeliefMass (conditionalize m E hAdm) i w phi)
    · have hn1 := (thresholdDecisionWallCount_eq_one_iff_straddles
        (m.c i)
        (modalNegativeBeliefMass m i w phi)
        (modalNegativeBeliefMass (conditionalize m E hAdm) i w phi)).2 hn
      simp [hp, hn, hp1, hn1]
    · have hn0 := (thresholdDecisionWallCount_eq_zero_iff_not_straddles
        (m.c i)
        (modalNegativeBeliefMass m i w phi)
        (modalNegativeBeliefMass (conditionalize m E hAdm) i w phi)).2 hn
      simp [hp, hn, hp1, hn0]
  · have hp0 := (thresholdDecisionWallCount_eq_zero_iff_not_straddles
      (m.c i)
      (modalPositiveBeliefMass m i w phi)
      (modalPositiveBeliefMass (conditionalize m E hAdm) i w phi)).2 hp
    by_cases hn : ThresholdStraddles (m.c i)
        (modalNegativeBeliefMass m i w phi)
        (modalNegativeBeliefMass (conditionalize m E hAdm) i w phi)
    · have hn1 := (thresholdDecisionWallCount_eq_one_iff_straddles
        (m.c i)
        (modalNegativeBeliefMass m i w phi)
        (modalNegativeBeliefMass (conditionalize m E hAdm) i w phi)).2 hn
      simp [hp, hn, hp0, hn1]
    · have hn0 := (thresholdDecisionWallCount_eq_zero_iff_not_straddles
        (m.c i)
        (modalNegativeBeliefMass m i w phi)
        (modalNegativeBeliefMass (conditionalize m E hAdm) i w phi)).2 hn
      simp [hp, hn, hp0, hn0]

/-- Two walls mean that both support coordinates straddle the Lockean threshold. -/
theorem conditionalization_belief_two_walls_iff_both_supports_straddle
    {W Ag Atom : Type} [DecidableEq W]
    (m : Model W Ag Atom) (E : Formula Atom Ag)
    (hAdm : ConditionalizationAdmissible m E)
    (i : Ag) (w : W) (phi : ModalFormula Atom Ag) :
    thresholdWallCount
        (evalModal m w (ModalFormula.bel i phi))
        (evalModal (conditionalize m E hAdm) w (ModalFormula.bel i phi)) = 2 ↔
      ConditionalizedPositiveStraddles m E hAdm i w phi ∧
      ConditionalizedNegativeStraddles m E hAdm i w phi := by
  rw [conditionalization_belief_wallCount_eq_supportWallCount]
  unfold ConditionalizedPositiveStraddles ConditionalizedNegativeStraddles
  by_cases hp : ThresholdStraddles (m.c i)
      (modalPositiveBeliefMass m i w phi)
      (modalPositiveBeliefMass (conditionalize m E hAdm) i w phi)
  · have hp1 := (thresholdDecisionWallCount_eq_one_iff_straddles
      (m.c i)
      (modalPositiveBeliefMass m i w phi)
      (modalPositiveBeliefMass (conditionalize m E hAdm) i w phi)).2 hp
    by_cases hn : ThresholdStraddles (m.c i)
        (modalNegativeBeliefMass m i w phi)
        (modalNegativeBeliefMass (conditionalize m E hAdm) i w phi)
    · have hn1 := (thresholdDecisionWallCount_eq_one_iff_straddles
        (m.c i)
        (modalNegativeBeliefMass m i w phi)
        (modalNegativeBeliefMass (conditionalize m E hAdm) i w phi)).2 hn
      simp [hp, hn, hp1, hn1]
    · have hn0 := (thresholdDecisionWallCount_eq_zero_iff_not_straddles
        (m.c i)
        (modalNegativeBeliefMass m i w phi)
        (modalNegativeBeliefMass (conditionalize m E hAdm) i w phi)).2 hn
      simp [hp, hn, hp1, hn0]
  · have hp0 := (thresholdDecisionWallCount_eq_zero_iff_not_straddles
      (m.c i)
      (modalPositiveBeliefMass m i w phi)
      (modalPositiveBeliefMass (conditionalize m E hAdm) i w phi)).2 hp
    by_cases hn : ThresholdStraddles (m.c i)
        (modalNegativeBeliefMass m i w phi)
        (modalNegativeBeliefMass (conditionalize m E hAdm) i w phi)
    · have hn1 := (thresholdDecisionWallCount_eq_one_iff_straddles
        (m.c i)
        (modalNegativeBeliefMass m i w phi)
        (modalNegativeBeliefMass (conditionalize m E hAdm) i w phi)).2 hn
      simp [hp, hn, hp0, hn1]
    · have hn0 := (thresholdDecisionWallCount_eq_zero_iff_not_straddles
        (m.c i)
        (modalNegativeBeliefMass m i w phi)
        (modalNegativeBeliefMass (conditionalize m E hAdm) i w phi)).2 hn
      simp [hp, hn, hp0, hn0]

/-- Any genuine belief-status change must be numerically witnessed by threshold
straddling on at least one support coordinate. -/
theorem conditionalization_belief_change_implies_support_straddle
    {W Ag Atom : Type} [DecidableEq W]
    (m : Model W Ag Atom) (E : Formula Atom Ag)
    (hAdm : ConditionalizationAdmissible m E)
    (i : Ag) (w : W) (phi : ModalFormula Atom Ag)
    (hChange :
      evalModal (conditionalize m E hAdm) w (ModalFormula.bel i phi) ≠
        evalModal m w (ModalFormula.bel i phi)) :
    ConditionalizedPositiveStraddles m E hAdm i w phi ∨
      ConditionalizedNegativeStraddles m E hAdm i w phi := by
  by_contra hNone
  have hNotPos : ¬ ConditionalizedPositiveStraddles m E hAdm i w phi := by
    intro hp
    exact hNone (Or.inl hp)
  have hNotNeg : ¬ ConditionalizedNegativeStraddles m E hAdm i w phi := by
    intro hn
    exact hNone (Or.inr hn)
  have hZero :=
    (conditionalization_belief_zero_walls_iff_no_support_straddles
      m E hAdm i w phi).2 ⟨hNotPos, hNotNeg⟩
  have hEq := (thresholdWallCount_eq_zero_iff _ _).1 hZero
  exact hChange hEq.symm

/-!
## Interpretation

The Boolean square is not disconnected from the underlying probability
semantics.  Its categorical wall count has an exact endpoint reading:

```text
0 walls -> neither support mass straddles threshold
1 wall  -> exactly one support mass straddles threshold
2 walls -> both support masses straddle threshold.
```

Thus every nontrivial belief transition carries a numerical witness in the
support masses.  What remains open is the genuinely continuous statement: if a
support mass varies continuously between straddling endpoints, then some
intermediate parameter must hit the threshold exactly.  That next step requires
a path/continuity layer not present in the current core formalization.

Working name: **Threshold-Straddle Geometry**.
-/

end PEL4
