import PEL4.SelfCorrectingPolicy

namespace PEL4

/-!
# Gate 98: model misspecification

Bayesian normalization does not imply model adequacy. A closed two-model class
can assign all posterior mass internally even when an observed long-run frequency
lies outside the tolerance region of every model in the class.
-/

inductive Gate98KnownModel where
  | low
  | high
  deriving DecidableEq, Repr

/-- Known models predict sharply separated positive frequencies. -/
def gate98PredictedPositive : Gate98KnownModel → Rat
  | .low => (1 : Rat) / 10
  | .high => (9 : Rat) / 10

/-- A balanced empirical frequency generated by an omitted process. -/
def gate98ObservedPositive : Rat := (1 : Rat) / 2

/-- Exact squared discrepancy, kept rational. -/
def gate98SquaredDiscrepancy (model : Gate98KnownModel) : Rat :=
  let d := gate98ObservedPositive - gate98PredictedPositive model
  d * d

/-- Tolerance for calling a model empirically adequate. -/
def gate98Tolerance : Rat := (1 : Rat) / 10

def gate98Fits (model : Gate98KnownModel) : Bool :=
  gate98SquaredDiscrepancy model ≤ gate98Tolerance

/-- A forced posterior over the closed class remains normalized. -/
structure Gate98ClosedPosterior where
  lowMass : Rat
  highMass : Rat
  deriving DecidableEq, Repr

/-- Symmetry leaves the two known models equally weighted. -/
def gate98ForcedPosterior : Gate98ClosedPosterior :=
  { lowMass := (1 : Rat) / 2, highMass := (1 : Rat) / 2 }

theorem gate98_discrepancies :
    gate98SquaredDiscrepancy .low = (4 : Rat) / 25 ∧
    gate98SquaredDiscrepancy .high = (4 : Rat) / 25 := by
  native_decide

theorem gate98_no_known_model_fits :
    gate98Fits .low = false ∧ gate98Fits .high = false := by
  native_decide

theorem gate98_forced_posterior_normalized :
    gate98ForcedPosterior.lowMass + gate98ForcedPosterior.highMass = 1 := by
  native_decide

theorem gate98_every_known_model_exceeds_tolerance :
    gate98SquaredDiscrepancy .low > gate98Tolerance ∧
    gate98SquaredDiscrepancy .high > gate98Tolerance := by
  native_decide

/-- Main Gate-98 theorem: posterior normalization within a closed model class can
coexist with the failure of every model in that class. -/
theorem gate98_normalized_but_misspecified :
    gate98ForcedPosterior.lowMass + gate98ForcedPosterior.highMass = 1 ∧
    gate98Fits .low = false ∧
    gate98Fits .high = false := by
  native_decide

/-!
## Boundary

The adequacy test is a finite rational witness based on squared discrepancy at an
empirical frequency. Gate 98 does not yet prove statistical consistency or a
frequentist goodness-of-fit theorem. It establishes the logical distinction
between normalized belief inside a class and adequacy of the class itself.
-/

end PEL4
