import PEL4.ExperimentDominancePruning

namespace PEL4

/-!
# Gate 73: sequential identifiability

Gate 67 showed that enriching an experiment menu can break a hidden-state alias.
Gate 73 isolates a stronger structural phenomenon: a hidden state may fail to be
identified by every single available test while becoming uniquely identifiable
from the joint signature of a short experiment sequence.

The witness has four hidden states carrying two latent bits. `firstBit` observes
only the first bit; `secondBit` observes only the second. Neither experiment is
injective on hidden states, while the two-experiment plan is.
-/

inductive Gate73Hidden where
  | s00
  | s01
  | s10
  | s11
  deriving DecidableEq, Repr

inductive Gate73Experiment where
  | firstBit
  | secondBit
  deriving DecidableEq, Repr

/-- Deterministic observation generated by one experiment. -/
def gate73Observe
    (experiment : Gate73Experiment)
    (state : Gate73Hidden) : Bool :=
  match experiment, state with
  | .firstBit, .s00 => false
  | .firstBit, .s01 => false
  | .firstBit, .s10 => true
  | .firstBit, .s11 => true
  | .secondBit, .s00 => false
  | .secondBit, .s01 => true
  | .secondBit, .s10 => false
  | .secondBit, .s11 => true

/-- Observation signature accumulated along a declared experiment plan. -/
def gate73Signature
    (plan : List Gate73Experiment)
    (state : Gate73Hidden) : List Bool :=
  plan.map fun experiment => gate73Observe experiment state

/-- A plan identifies all hidden states exactly when its observation signature is
injective. -/
def Gate73PlanIdentifies (plan : List Gate73Experiment) : Prop :=
  Function.Injective (gate73Signature plan)

/-- Measuring only the first latent coordinate leaves the second coordinate
aliased. -/
theorem gate73_first_bit_not_identifying :
    ¬ Gate73PlanIdentifies [.firstBit] := by
  intro h
  have hEq : Gate73Hidden.s00 = Gate73Hidden.s01 :=
    h (by native_decide)
  cases hEq

/-- Measuring only the second coordinate leaves the first coordinate aliased. -/
theorem gate73_second_bit_not_identifying :
    ¬ Gate73PlanIdentifies [.secondBit] := by
  intro h
  have hEq : Gate73Hidden.s00 = Gate73Hidden.s10 :=
    h (by native_decide)
  cases hEq

/-- The two-step signature records both latent bits and is injective. -/
theorem gate73_two_step_plan_identifies :
    Gate73PlanIdentifies [.firstBit, .secondBit] := by
  intro left right h
  cases left <;> cases right <;> native_decide

/-- Reversing the order preserves identifiability because both coordinates are
still observed. -/
theorem gate73_reversed_two_step_plan_identifies :
    Gate73PlanIdentifies [.secondBit, .firstBit] := by
  intro left right h
  cases left <;> cases right <;> native_decide

/-- Every hidden state receives a distinct two-bit signature. -/
theorem gate73_two_step_signatures :
    gate73Signature [.firstBit, .secondBit] .s00 = [false, false] ∧
    gate73Signature [.firstBit, .secondBit] .s01 = [false, true] ∧
    gate73Signature [.firstBit, .secondBit] .s10 = [true, false] ∧
    gate73Signature [.firstBit, .secondBit] .s11 = [true, true] := by
  native_decide

/-- Main Gate-73 theorem: one-shot non-identifiability does not imply sequential
non-identifiability. Two individually insufficient experiments can jointly form
an identifying plan. -/
theorem gate73_sequential_identifiability :
    ¬ Gate73PlanIdentifies [.firstBit] ∧
    ¬ Gate73PlanIdentifies [.secondBit] ∧
    Gate73PlanIdentifies [.firstBit, .secondBit] ∧
    Gate73PlanIdentifies [.secondBit, .firstBit] := by
  exact ⟨gate73_first_bit_not_identifying,
    gate73_second_bit_not_identifying,
    gate73_two_step_plan_identifies,
    gate73_reversed_two_step_plan_identifies⟩

/-!
## Gate-73 boundary

The witness is deterministic and finite. It establishes a structural distinction
between one-shot and sequential identifiability, not a stochastic asymptotic
learning theorem. Gate 74 adds the quantitative question: how many repeated
observations are required to cross a chosen posterior-confidence target?
-/

end PEL4
