import PEL4.TopologicalEvidenceKripke

namespace PEL4

/-!
# Evidence stability as Alexandrov local constancy

The preceding gate established two facts:

1. on reflexive/transitive finite frames, `topBox` is the ordinary FDE/Kripke
   box;
2. the repository's evidence-stable knowledge can still diverge from that box.

This module identifies the extra ingredient exactly.

The Boolean predicate `accessibleFDEValueStable` says that the complete
FDE-valued interpretation is constant on the successor neighbourhood `R(w)`.
For the Alexandrov topology generated by a preorder, `R(w)` is the minimal open
neighbourhood of `w`. Hence this stability test is naturally read as local
constancy of the complete four-valued evidence state.

Algebraically, evidence-stable knowledge then factorizes as

```text
K_stable(phi)
  = Box_FDE(phi) AND_FDE ConstancyGuard(phi),
```

where the guard is crisp `T` when the accessible FDE profile is locally
constant and crisp `F` otherwise.

This gives a geometric reading of the non-standard knowledge operator without
requiring a second accessibility relation or a second modal primitive.
-/

/-- The complete FDE-valued profile is constant on the successor neighbourhood of `w`. -/
def SuccessorLocallyConstantAt {W : Type}
    (R : W → FiniteSet W) (value : W → FDEValue) (w : W) : Prop :=
  ∀ u, u ∈ R w → ∀ v, v ∈ R w → value u = value v

/--
The repository's Boolean accessible-value stability test is exactly constancy
on the successor neighbourhood.
-/
theorem modal_stability_iff_successor_local_constancy
    {W : Type} [DecidableEq W]
    (R : W → FiniteSet W) (value : W → FDEValue) (w : W) :
    modalAccessibleValueStable (R w) value = true ↔
      SuccessorLocallyConstantAt R value w := by
  cases hR : R w with
  | nil =>
      simp [SuccessorLocallyConstantAt, modalAccessibleValueStable, hR]
  | cons first rest =>
      constructor
      · intro hStable u hu v hv
        have hStableRest : ∀ x, x ∈ rest → value x = value first := by
          rw [hR] at hStable
          unfold modalAccessibleValueStable at hStable
          simp only [List.all_eq_true] at hStable
          intro x hx
          have hEq := hStable x hx
          simpa using hEq
        have huCases : u = first ∨ u ∈ rest := by
          simpa [hR] using hu
        have hvCases : v = first ∨ v ∈ rest := by
          simpa [hR] using hv
        have huEq : value u = value first := by
          cases huCases with
          | inl h => simpa [h]
          | inr h => exact hStableRest u h
        have hvEq : value v = value first := by
          cases hvCases with
          | inl h => simpa [h]
          | inr h => exact hStableRest v h
        exact huEq.trans hvEq.symm
      · intro hConst
        rw [hR]
        unfold modalAccessibleValueStable
        simp only [List.all_eq_true]
        intro x hx
        have hEq : value x = value first :=
          hConst x (by simp [hR, hx]) first (by simp [hR])
        simpa using hEq

/-- Crisp FDE guard for local evidence constancy. -/
def stabilityGuard (stable : Bool) : FDEValue :=
  if stable then FDEValue.T else FDEValue.F

/-- The constancy guard is strict true exactly in the stable phase. -/
theorem stabilityGuard_true :
    stabilityGuard true = FDEValue.T := by
  rfl

/-- The constancy guard is strict false exactly in the unstable phase. -/
theorem stabilityGuard_false :
    stabilityGuard false = FDEValue.F := by
  rfl

/--
Exact algebraic factorization of evidence-stable knowledge.

When the accessible FDE profile is stable, conjunction with `T` leaves the
ordinary Box unchanged. When it is unstable, conjunction with `F` collapses the
result to strict falsity.
-/
theorem evidence_stable_knowledge_factorization
    {W Ag Atom : Type} [DecidableEq W]
    (m : Model W Ag Atom) (i : Ag) (w : W) (phi : Formula Atom Ag) :
    evidenceStableKnowledgeValue m i w phi =
      FDEValue.and
        (standardFDEBoxValue m i w phi)
        (stabilityGuard (accessibleFDEValueStable m i w phi)) := by
  cases hStable : accessibleFDEValueStable m i w phi <;>
    simp [evidenceStableKnowledgeValue, evidenceStableKnowledgePositive,
      evidenceStableKnowledgeNegative, standardFDEBoxValue,
      stabilityGuard, FDEValue.and, hStable]

/-- Local constancy recovers the ordinary FDE Box exactly. -/
theorem evidence_stable_knowledge_eq_standard_box_of_local_constancy
    {W Ag Atom : Type} [DecidableEq W]
    (m : Model W Ag Atom) (i : Ag) (w : W) (phi : Formula Atom Ag)
    (hConst : SuccessorLocallyConstantAt (m.R i)
      (fun u => eval m u phi) w) :
    evidenceStableKnowledgeValue m i w phi =
      standardFDEBoxValue m i w phi := by
  have hStable : accessibleFDEValueStable m i w phi = true :=
    (modal_stability_iff_successor_local_constancy
      (m.R i) (fun u => eval m u phi) w).2 hConst
  exact evidence_stable_knowledge_eq_standard_box_of_stable
    m i w phi hStable

/-- Failure of local constancy forces evidence-stable knowledge to strict `F`. -/
theorem evidence_stable_knowledge_eq_false_of_not_local_constancy
    {W Ag Atom : Type} [DecidableEq W]
    (m : Model W Ag Atom) (i : Ag) (w : W) (phi : Formula Atom Ag)
    (hNotConst : ¬ SuccessorLocallyConstantAt (m.R i)
      (fun u => eval m u phi) w) :
    evidenceStableKnowledgeValue m i w phi = FDEValue.F := by
  have hStable : accessibleFDEValueStable m i w phi = false := by
    cases hs : accessibleFDEValueStable m i w phi with
    | false => rfl
    | true =>
        have hConst : SuccessorLocallyConstantAt (m.R i)
            (fun u => eval m u phi) w :=
          (modal_stability_iff_successor_local_constancy
            (m.R i) (fun u => eval m u phi) w).1 hs
        exact False.elim (hNotConst hConst)
  exact knowledge_instability_forces_false m i w phi hStable

/--
On an S4-style successor frame, topological Box represents evidence-stable
knowledge whenever the complete FDE profile is locally constant.
-/
theorem topological_box_represents_stable_knowledge_of_local_constancy
    {W Ag Atom : Type} [DecidableEq W]
    (m : Model W Ag Atom) (i : Ag)
    (hRefl : SuccessorReflexive (m.R i))
    (hTrans : SuccessorTransitive (m.R i))
    (w : W) (phi : Formula Atom Ag)
    (hConst : SuccessorLocallyConstantAt (m.R i)
      (fun u => eval m u phi) w) :
    TopologicalEvidenceRepresentsAt
      (topBox (successorInteriorSemantics (m.R i) hRefl hTrans)
        (kripkeEvidence (fun u => eval m u phi)))
      w (evidenceStableKnowledgeValue m i w phi) := by
  have hEq := evidence_stable_knowledge_eq_standard_box_of_local_constancy
    m i w phi hConst
  rw [hEq]
  exact topological_box_represents_standard_box
    m i hRefl hTrans w phi

/--
The universal S4 contrast model from Gate 3 is explicitly non-locally-constant
at the root: its accessible complete values include both `T` and `B`.
-/
theorem topological_knowledge_gate_not_locally_constant :
    ¬ SuccessorLocallyConstantAt
      (TopologicalKnowledgeGateModel.R KnowledgeGateAgent.a)
      (fun u => eval TopologicalKnowledgeGateModel u knowledgeGateP)
      KnowledgeGateWorld.root := by
  intro hConst
  have hEq := hConst KnowledgeGateWorld.left (by native_decide)
    KnowledgeGateWorld.right (by native_decide)
  have hTB :
      eval TopologicalKnowledgeGateModel KnowledgeGateWorld.left knowledgeGateP =
        eval TopologicalKnowledgeGateModel KnowledgeGateWorld.right knowledgeGateP :=
    hEq
  native_decide at hTB

/--
The earlier `B` versus `F` divergence is therefore explained exactly by local
non-constancy, not by failure of reflexivity or transitivity.
-/
theorem topological_knowledge_gate_false_from_nonconstancy :
    evidenceStableKnowledgeValue TopologicalKnowledgeGateModel KnowledgeGateAgent.a
      KnowledgeGateWorld.root knowledgeGateP = FDEValue.F := by
  exact evidence_stable_knowledge_eq_false_of_not_local_constancy
    TopologicalKnowledgeGateModel KnowledgeGateAgent.a
    KnowledgeGateWorld.root knowledgeGateP
    topological_knowledge_gate_not_locally_constant

/-!
## Interpretation

The topological research branch now has a two-layer semantics that can be stated
without metaphor:

```text
raw modal robustness:
  Box_top(phi) = Box_FDE(phi)

epistemic robustness:
  K_stable(phi)
    = Box_FDE(phi) AND_FDE ConstancyGuard(phi)
```

For a reflexive/transitive relation, the successor set `R(w)` is the minimal
Alexandrov neighbourhood of `w`. Therefore `SuccessorLocallyConstantAt` is the
finite preorder version of local constancy of the complete evidence map

```text
w |-> value(phi,w) in {T,F,B,N}.
```

This sharpens the conclusion of Gate 3. A second topology is not yet required:
the existing evidence-stability clause already has a natural geometric reading
inside the same Alexandrov space. The crucial distinction is between

* **truth-region robustness**, captured coordinatewise by interior/closure; and
* **value-profile constancy**, which asks the complete four-valued state not to
  change within the local neighbourhood.

A natural next gate is to move beyond Alexandrov spaces and define genuine local
constancy for arbitrary `InteriorSemantics`. That would test whether
`K_stable = Box_top AND_FDE ConstancyGuard` survives without a privileged
minimal neighbourhood.
-/

end PEL4
