import PEL4.TopologicalEvidenceSierpinski
import PEL4.KnowledgeSemantics

namespace PEL4

/-!
# Alexandrov/Kripke representation gate

This module connects the experimental topological evidence semantics to the
repository's finite Kripke semantics.

Given a reflexive and transitive successor relation `R`, define

```text
Int(A)(w)  iff  every R-successor of w lies in A.
```

This is the Alexandrov interior associated with the preorder. Its dual closure
then says, classically,

```text
Cl(A)(w)  iff  some R-successor of w lies in A.
```

For a two-channel FDE evidence profile this immediately gives

```text
Box(P,N)(w)
  = (all successors positively support the formula,
     some successor negatively supports the formula),
```

which is exactly the ordinary Belnap-Dunn/Kripke box. The final section then
shows why the repository's evidence-stable `know` operator is genuinely
stronger: even on a reflexive and transitive frame it can reject a heterogeneous
accessible FDE profile that the topological/raw box accepts.
-/

/-- Global reflexivity of a finite successor relation. -/
def SuccessorReflexive {W : Type} [DecidableEq W]
    (R : W → FiniteSet W) : Prop :=
  ∀ w, w ∈ R w

/-- Global transitivity of a finite successor relation. -/
def SuccessorTransitive {W : Type} [DecidableEq W]
    (R : W → FiniteSet W) : Prop :=
  ∀ w u, u ∈ R w → ∀ v, v ∈ R u → v ∈ R w

/-- Alexandrov-style interior generated by a successor relation. -/
def successorInterior {W : Type} [DecidableEq W]
    (R : W → FiniteSet W) (A : EvidenceRegion W) : EvidenceRegion W :=
  fun w => ∀ u, u ∈ R w → A u

/--
A reflexive, transitive successor relation generates an algebraic interior
semantics. Reflexivity gives `Int A ⊆ A`; transitivity gives the forward half
of idempotence, while reflexivity at successors gives the reverse half.
-/
def successorInteriorSemantics {W : Type} [DecidableEq W]
    (R : W → FiniteSet W)
    (hRefl : SuccessorReflexive R)
    (hTrans : SuccessorTransitive R) : InteriorSemantics W :=
  { interior := successorInterior R
  , interior_subset := by
      intro A w h
      exact h w (hRefl w)
  , interior_monotone := by
      intro A B hAB w hA u hu
      exact hAB u (hA u hu)
  , interior_idempotent := by
      intro A w
      constructor
      · intro h u hu
        exact h u hu u (hRefl u)
      · intro h u hu v hv
        exact h v (hTrans w u hu v hv)
  , interior_top := by
      intro w u hu
      exact True.intro
  , interior_intersection := by
      intro A B w
      constructor
      · intro h
        constructor
        · intro u hu
          exact (h u hu).1
        · intro u hu
          exact (h u hu).2
      · rintro ⟨hA, hB⟩ u hu
        exact ⟨hA u hu, hB u hu⟩
  }

/--
In the Alexandrov semantics, closure at a point is existential accessibility.
This is the topological dual of universal successor interior.
-/
theorem successor_closure_iff_exists
    {W : Type} [DecidableEq W]
    (R : W → FiniteSet W)
    (hRefl : SuccessorReflexive R)
    (hTrans : SuccessorTransitive R)
    (A : EvidenceRegion W) (w : W) :
    (successorInteriorSemantics R hRefl hTrans).closure A w ↔
      ∃ u, u ∈ R w ∧ A u := by
  classical
  change (¬ ∀ u, u ∈ R w → ¬ A u) ↔ ∃ u, u ∈ R w ∧ A u
  constructor
  · intro h
    by_contra hNone
    apply h
    intro u hu hA
    exact hNone ⟨u, hu, hA⟩
  · rintro ⟨u, hu, hA⟩ hAll
    exact hAll u hu hA

/-- Turn an arbitrary FDE-valued interpretation into positive/negative regions. -/
def kripkeEvidence {W : Type}
    (value : W → FDEValue) : TopologicalEvidence W :=
  { pos := fun w => (value w).pos = true
  , neg := fun w => (value w).neg = true
  }

/-- Ordinary raw FDE box over a finite successor relation. -/
def rawFDEBoxValue {W : Type}
    (R : W → FiniteSet W) (w : W) (value : W → FDEValue) : FDEValue :=
  { pos := (R w).all (fun u => (value u).pos)
  , neg := (R w).any (fun u => (value u).neg)
  }

/--
Representation theorem: on every reflexive and transitive finite frame, the
topological Box generated from the successor Alexandrov interior semantically
represents the ordinary raw FDE/Kripke box.
-/
theorem successor_topBox_represents_raw_fde_box
    {W : Type} [DecidableEq W]
    (R : W → FiniteSet W)
    (hRefl : SuccessorReflexive R)
    (hTrans : SuccessorTransitive R)
    (value : W → FDEValue) (w : W) :
    TopologicalEvidenceRepresentsAt
      (topBox (successorInteriorSemantics R hRefl hTrans)
        (kripkeEvidence value))
      w (rawFDEBoxValue R w value) := by
  constructor
  · change (∀ u, u ∈ R w → (value u).pos = true) ↔
      (R w).all (fun u => (value u).pos) = true
    simp only [List.all_eq_true]
  · change (successorInteriorSemantics R hRefl hTrans).closure
        (kripkeEvidence value).neg w ↔
      (R w).any (fun u => (value u).neg) = true
    rw [successor_closure_iff_exists R hRefl hTrans]
    change (∃ u, u ∈ R w ∧ (value u).neg = true) ↔
      (R w).any (fun u => (value u).neg) = true
    simp only [List.any_eq_true]

/-- Package the repository's existing positive/negative standard Box tests. -/
def standardFDEBoxValue
    {W Ag Atom : Type} [DecidableEq W]
    (m : Model W Ag Atom) (i : Ag) (w : W) (phi : Formula Atom Ag) : FDEValue :=
  { pos := standardBoxPositive m i w phi
  , neg := standardBoxNegative m i w phi
  }

/-- The generic raw box specializes definitionally to the repository's standard Box. -/
theorem raw_fde_box_eq_standard_box
    {W Ag Atom : Type} [DecidableEq W]
    (m : Model W Ag Atom) (i : Ag) (w : W) (phi : Formula Atom Ag) :
    rawFDEBoxValue (m.R i) w (fun u => eval m u phi) =
      standardFDEBoxValue m i w phi := by
  rfl

/--
Formula-level corollary: on an S4-style frame, the topological Box represents
the existing standard FDE Box value for every legacy formula.
-/
theorem topological_box_represents_standard_box
    {W Ag Atom : Type} [DecidableEq W]
    (m : Model W Ag Atom) (i : Ag)
    (hRefl : SuccessorReflexive (m.R i))
    (hTrans : SuccessorTransitive (m.R i))
    (w : W) (phi : Formula Atom Ag) :
    TopologicalEvidenceRepresentsAt
      (topBox (successorInteriorSemantics (m.R i) hRefl hTrans)
        (kripkeEvidence (fun u => eval m u phi)))
      w (standardFDEBoxValue m i w phi) := by
  have h := successor_topBox_represents_raw_fde_box
    (m.R i) hRefl hTrans (fun u => eval m u phi) w
  rw [raw_fde_box_eq_standard_box m i w phi] at h
  exact h

/--
When the accessible complete FDE profile is stable, evidence-stable knowledge
collapses to the ordinary standard Box. Thus the topological representation is
also a representation of `know` on the homogeneous/stable fragment.
-/
theorem evidence_stable_knowledge_eq_standard_box_of_stable
    {W Ag Atom : Type} [DecidableEq W]
    (m : Model W Ag Atom) (i : Ag) (w : W) (phi : Formula Atom Ag)
    (hStable : accessibleFDEValueStable m i w phi = true) :
    evidenceStableKnowledgeValue m i w phi =
      standardFDEBoxValue m i w phi := by
  simp [evidenceStableKnowledgeValue, evidenceStableKnowledgePositive,
    evidenceStableKnowledgeNegative, standardFDEBoxValue,
    standardBoxPositive, standardBoxNegative, hStable]

/-!
## A reflexive/transitive separation model

The original knowledge gate has a non-reflexive root. To show that the
separation from topological/raw Box is not merely a frame artifact, we use the
same `T/T/B` valuation on the universal three-world relation. This relation is
reflexive and transitive, hence generates an Alexandrov topology.

The accessible profile is heterogeneous, so evidence-stable knowledge returns
strict `F`. But every world has positive support and one world has negative
support, so the standard/topological Box returns the glut `B`.
-/

/-- Universal S4-frame variant of the finite knowledge contrast model. -/
def TopologicalKnowledgeGateModel :
    Model KnowledgeGateWorld KnowledgeGateAgent KnowledgeGateAtom :=
  { worlds := [KnowledgeGateWorld.root,
      KnowledgeGateWorld.left, KnowledgeGateWorld.right]
  , R := fun _ _ => [KnowledgeGateWorld.root,
      KnowledgeGateWorld.left, KnowledgeGateWorld.right]
  , mu := fun _ _ => knowledgeGateMu
  , val := knowledgeGateVal
  , c := fun _ => 2 / 3
  , mu_total := by
      intro _ _
      native_decide
  , mu_empty := by
      intro _ _
      native_decide
  , c_gt_half := by
      intro _
      native_decide
  , c_le_one := by
      intro _
      native_decide
  }

/-- The universal contrast relation is reflexive. -/
theorem topological_knowledge_gate_reflexive :
    SuccessorReflexive
      (TopologicalKnowledgeGateModel.R KnowledgeGateAgent.a) := by
  intro w
  cases w <;> simp [TopologicalKnowledgeGateModel]

/-- The universal contrast relation is transitive. -/
theorem topological_knowledge_gate_transitive :
    SuccessorTransitive
      (TopologicalKnowledgeGateModel.R KnowledgeGateAgent.a) := by
  intro w u hu v hv
  cases v <;> simp [TopologicalKnowledgeGateModel]

/-- The standard/raw FDE Box is glutty `B` on the heterogeneous universal profile. -/
theorem topological_knowledge_gate_standard_box_is_both :
    standardFDEBoxValue TopologicalKnowledgeGateModel KnowledgeGateAgent.a
      KnowledgeGateWorld.root knowledgeGateP = FDEValue.B := by
  native_decide

/-- Evidence-stable knowledge rejects the same heterogeneous profile as strict `F`. -/
theorem topological_knowledge_gate_stable_knowledge_is_false :
    evidenceStableKnowledgeValue TopologicalKnowledgeGateModel KnowledgeGateAgent.a
      KnowledgeGateWorld.root knowledgeGateP = FDEValue.F := by
  native_decide

/-- The Alexandrov topological Box semantically represents `B` at the root. -/
theorem topological_knowledge_gate_topBox_represents_both :
    TopologicalEvidenceRepresentsAt
      (topBox
        (successorInteriorSemantics
          (TopologicalKnowledgeGateModel.R KnowledgeGateAgent.a)
          topological_knowledge_gate_reflexive
          topological_knowledge_gate_transitive)
        (kripkeEvidence
          (fun u => eval TopologicalKnowledgeGateModel u knowledgeGateP)))
      KnowledgeGateWorld.root FDEValue.B := by
  have h := topological_box_represents_standard_box
    TopologicalKnowledgeGateModel KnowledgeGateAgent.a
    topological_knowledge_gate_reflexive
    topological_knowledge_gate_transitive
    KnowledgeGateWorld.root knowledgeGateP
  rw [topological_knowledge_gate_standard_box_is_both] at h
  exact h

/--
Separation theorem: even on a reflexive and transitive frame, topological/raw
Box and evidence-stable knowledge disagree on heterogeneous evidence.
-/
theorem topological_box_and_stable_knowledge_diverge_on_s4_frame :
    TopologicalEvidenceRepresentsAt
      (topBox
        (successorInteriorSemantics
          (TopologicalKnowledgeGateModel.R KnowledgeGateAgent.a)
          topological_knowledge_gate_reflexive
          topological_knowledge_gate_transitive)
        (kripkeEvidence
          (fun u => eval TopologicalKnowledgeGateModel u knowledgeGateP)))
      KnowledgeGateWorld.root FDEValue.B ∧
    evidenceStableKnowledgeValue TopologicalKnowledgeGateModel KnowledgeGateAgent.a
      KnowledgeGateWorld.root knowledgeGateP = FDEValue.F := by
  exact ⟨topological_knowledge_gate_topBox_represents_both,
    topological_knowledge_gate_stable_knowledge_is_false⟩

/-!
## Interpretation

Gate 3 gives a precise bridge and a precise obstruction.

**Bridge.** On reflexive/transitive finite Kripke frames, the successor
Alexandrov topology turns the candidate topological semantics

```text
Box(P,N) = (Int P, Cl N)
```

into the ordinary FDE modal box

```text
(all accessible positive support, some accessible negative support).
```

**Stable-fragment recovery.** Whenever the complete accessible FDE value is
homogeneous, the repository's evidence-stable knowledge operator collapses to
that same standard/topological box.

**Obstruction.** Frame conditions alone do not identify `know` with topological
Box. Even on the universal three-world S4 frame, the heterogeneous `T/T/B`
profile gives

```text
topological/raw Box = B
stable know         = F.
```

So the extra epistemic ingredient in 4PEL knowledge is not topology of
accessibility alone. It is a second condition on the variation of the complete
FDE evidence state over a neighbourhood.

This suggests the next research object: a topology on worlds together with a
second topology, uniformity, or sheaf-like local constancy condition on FDE
evidence profiles. That is where the evidence-stability clause may acquire a
geometric semantics of its own.
-/

end PEL4
