import PEL4.TruthCalibrationBridge

namespace PEL4

#print axioms bridgeRobustRecovery_implies_zeroCalibration
#print axioms bridgeRobustRecovery_implies_truthAligned
#print axioms gate54_recovery_alone_does_not_imply_truth
#print axioms gate54_robust_state_is_bridgeRobust
#print axioms gate54_robust_state_zero_calibration
#print axioms gate54_robust_state_truth_aligned
#print axioms gate54_gate53_robust_target_is_truth_certified
#print axioms gate54_recovery_truth_boundary

end PEL4
