import PEL4.Paradoxes.ChurchFitchPhaseLandscape

namespace PEL4

/-!
# Church--Fitch classification layer

The preceding gates establish three distinct facts:

* positive/designated raw knowability plus the source no-gap bridge and uniform
  witness recovery forces positive omniscience;
* restricting truth to strict `T` weakens the knowability premise needed for the
  same positive conclusion over strict truths, and source no-glut upgrades the
  conclusion to strict `T` knowledge;
* primitive raw possibility is strictly more informative than positive internal
  dual possibility, because the latter can be generated by epistemic
  instability without an accessible positive witness.

This module packages those results as a compact phase classification rather than
introducing another paradox witness.
-/

/-- Positive/designated knowability formulated with the internal knowledge dual
instead of primitive raw possibility. -/
def ModalPositiveDualKnowabilityPrinciple
    {W Ag Atom : Type} [DecidableEq W]
    (m : Model W Ag Atom) (i : Ag) : Prop :=
  ∀ (w : W) (phi : ModalFormula Atom Ag),
    w ∈ m.worlds →
    modalPositiveAt m w phi →
    modalDualPositiveKnowableAt m i w phi

/-- Strict-truth restriction of the dualized knowability principle. -/
def ModalStrictTruthDualKnowabilityPrinciple
    {W Ag Atom : Type} [DecidableEq W]
    (m : Model W Ag Atom) (i : Ag) : Prop :=
  ∀ (w : W) (phi : ModalFormula Atom Ag),
    w ∈ m.worlds →
    modalStrictTrueAt m w phi →
    modalDualPositiveKnowableAt m i w phi

/-- Raw positive knowability implies dualized positive knowability pointwise,
so the raw schema implies the dualized schema. -/
theorem positive_raw_knowability_implies_positive_dual_knowability
    {W Ag Atom : Type} [DecidableEq W]
    (m : Model W Ag Atom) (i : Ag)
    (hRaw : ModalPositiveKnowabilityPrinciple m i) :
    ModalPositiveDualKnowabilityPrinciple m i := by
  intro w phi hw hTrue
  exact modal_raw_positive_knowability_implies_dual_positive_knowability
    m i w phi (hRaw w phi hw hTrue)

/-- Raw knowability restricted to strict truths also implies the corresponding
dualized strict-truth schema. -/
theorem strict_truth_raw_knowability_implies_strict_truth_dual_knowability
    {W Ag Atom : Type} [DecidableEq W]
    (m : Model W Ag Atom) (i : Ag)
    (hRaw : ModalStrictTruthPositiveKnowabilityPrinciple m i) :
    ModalStrictTruthDualKnowabilityPrinciple m i := by
  intro w phi hw hTrue
  exact modal_raw_positive_knowability_implies_dual_positive_knowability
    m i w phi (hRaw w phi hw hTrue)

/-- Positive dualized knowability trivially weakens to its strict-truth
restriction because strict truth implies positive/designated truth. -/
theorem positive_dual_knowability_implies_strict_truth_dual_knowability
    {W Ag Atom : Type} [DecidableEq W]
    (m : Model W Ag Atom) (i : Ag)
    (hDual : ModalPositiveDualKnowabilityPrinciple m i) :
    ModalStrictTruthDualKnowabilityPrinciple m i := by
  intro w phi hw hTrue
  exact hDual w phi hw (modal_strict_true_implies_positive m w phi hTrue)

/-- Positive omniscience entails positive knowledge of every strict truth. -/
theorem positive_omniscience_implies_strict_truth_positive_omniscience
    {W Ag Atom : Type} [DecidableEq W]
    (m : Model W Ag Atom) (i : Ag)
    (hOmni : ModalPositiveOmniscience m i) :
    ModalStrictTruthPositiveOmniscience m i := by
  intro w phi hw hTrue
  exact hOmni w phi hw (modal_strict_true_implies_positive m w phi hTrue)

/-- Strict `T` knowledge of every strict truth entails positive knowledge of
every strict truth. -/
theorem strict_knowledge_omniscience_implies_strict_truth_positive_omniscience
    {W Ag Atom : Type} [DecidableEq W]
    (m : Model W Ag Atom) (i : Ag)
    (hOmni : ModalStrictKnowledgeOmniscience m i) :
    ModalStrictTruthPositiveOmniscience m i := by
  intro w phi hw hTrue
  unfold modalPositiveKnownAt
  rw [hOmni w phi hw hTrue]
  rfl

/-- Complete raw-positive phase under the strongest common recovery package.

A formula-wide positive raw knowability principle yields positive omniscience.
The same premise therefore also yields positive knowledge of all strict truths,
and with source no-glut it yields strict `T` knowledge of all strict truths. -/
theorem church_fitch_positive_raw_phase_classification
    {W Ag Atom : Type} [DecidableEq W]
    (m : Model W Ag Atom) (i : Ag)
    (hKnowability : ModalPositiveKnowabilityPrinciple m i)
    (hNoGap : ∀ (w : W) (phi : ModalFormula Atom Ag),
      w ∈ m.worlds → ModalKnowledgeNoGapAt m i w phi)
    (hRecovery : ModalUniformFitchRecovery m i)
    (hSourceNoGlut : ∀ (w : W) (phi : ModalFormula Atom Ag),
      w ∈ m.worlds → ModalKnowledgeNoGlutAt m i w phi) :
    ModalPositiveOmniscience m i ∧
    ModalStrictTruthPositiveOmniscience m i ∧
    ModalStrictKnowledgeOmniscience m i := by
  have hPositive : ModalPositiveOmniscience m i :=
    church_fitch_positive_omniscience_of_knowability
      m i hKnowability hNoGap hRecovery
  have hStrictRaw : ModalStrictTruthPositiveKnowabilityPrinciple m i :=
    positive_knowability_implies_strict_truth_positive_knowability
      m i hKnowability
  have hStrictPositive : ModalStrictTruthPositiveOmniscience m i :=
    church_fitch_strict_truth_positive_omniscience_of_strict_knowability
      m i hStrictRaw hNoGap hRecovery
  have hStrict : ModalStrictKnowledgeOmniscience m i :=
    church_fitch_strict_knowledge_omniscience_of_strict_knowability
      m i hStrictRaw hNoGap hRecovery hSourceNoGlut
  exact ⟨hPositive, hStrictPositive, hStrict⟩

/-- Restricted strict-truth raw knowability already classifies both strict-truth
conclusions under source no-gap, uniform recovery, and source no-glut. -/
theorem church_fitch_strict_raw_phase_classification
    {W Ag Atom : Type} [DecidableEq W]
    (m : Model W Ag Atom) (i : Ag)
    (hKnowability : ModalStrictTruthPositiveKnowabilityPrinciple m i)
    (hNoGap : ∀ (w : W) (phi : ModalFormula Atom Ag),
      w ∈ m.worlds → ModalKnowledgeNoGapAt m i w phi)
    (hRecovery : ModalUniformFitchRecovery m i)
    (hSourceNoGlut : ∀ (w : W) (phi : ModalFormula Atom Ag),
      w ∈ m.worlds → ModalKnowledgeNoGlutAt m i w phi) :
    ModalStrictTruthPositiveOmniscience m i ∧
    ModalStrictKnowledgeOmniscience m i := by
  constructor
  · exact church_fitch_strict_truth_positive_omniscience_of_strict_knowability
      m i hKnowability hNoGap hRecovery
  · exact church_fitch_strict_knowledge_omniscience_of_strict_knowability
      m i hKnowability hNoGap hRecovery hSourceNoGlut

/-- The finite phase witness records the strict separation between dualized and
raw knowability: dual-positive knowability can hold for a strict truth while raw
positive knowability fails. -/
theorem church_fitch_dual_raw_separation_witness :
    modalStrictTrueAt FitchDualModel FitchDualWorld.root fitchP ∧
    modalDualPositiveKnowableAt
      FitchDualModel FitchAgent.a FitchDualWorld.root fitchP ∧
    ¬ modalPositiveKnowableAt
      FitchDualModel FitchAgent.a FitchDualWorld.root fitchP :=
  fitch_dual_knowability_without_raw_knowability

/-!
## Classification summary

The verified implication structure is therefore:

  positive raw knowability
      -> strict-truth raw knowability
      -> strict-truth dual knowability

and also

  positive raw knowability
      -> positive dual knowability
      -> strict-truth dual knowability.

On the conclusion side:

  positive omniscience
      -> positive knowledge of all strict truths,

while

  strict knowledge omniscience
      -> positive knowledge of all strict truths.

Under source no-gap and uniform witness recovery, raw knowability supports the
Church--Fitch collapse because it exposes an accessible positive knowledge
witness.  Dualized knowability has no such general witness guarantee.  The
finite `FitchDualModel` makes that failure explicit.

Thus the phase landscape should not be read as four interchangeable versions of
the same theorem.  The truth axis changes premise strength, while the possibility
axis changes the semantic content of "possible" itself.
-/

end PEL4
