import PEL4.Model
import PEL4.Belief
import PEL4.Syntax

namespace PEL4.Paradoxes

/-- Three representative claims from a fallible book. -/
inductive PrefaceAtom where
  | p1 | p2 | p3
deriving DecidableEq, Repr

inductive P_Agent where
  | author
deriving DecidableEq, Repr

/--
`allCorrect` is the world in which every representative claim is correct.
Each `errorN` world contains exactly one local error.  The model therefore
separates high confidence in every individual claim from lower confidence in
their conjunction.
-/
inductive P_World where
  | allCorrect | error1 | error2 | error3
deriving DecidableEq, Repr

/-- Classical object-level valuation embedded into FDE. -/
def preface_val : P_World → PrefaceAtom → FDEValue
| P_World.allCorrect, _ => FDEValue.T
| P_World.error1, PrefaceAtom.p1 => FDEValue.F
| P_World.error1, PrefaceAtom.p2 => FDEValue.T
| P_World.error1, PrefaceAtom.p3 => FDEValue.T
| P_World.error2, PrefaceAtom.p1 => FDEValue.T
| P_World.error2, PrefaceAtom.p2 => FDEValue.F
| P_World.error2, PrefaceAtom.p3 => FDEValue.T
| P_World.error3, PrefaceAtom.p1 => FDEValue.T
| P_World.error3, PrefaceAtom.p2 => FDEValue.T
| P_World.error3, PrefaceAtom.p3 => FDEValue.F

/-- Uniform probability over the four epistemically accessible possibilities. -/
def preface_mu : FiniteSet P_World → Rat
| S =>
  let p0 := if S.contains P_World.allCorrect then (1 : Rat) / 4 else 0
  let p1 := if S.contains P_World.error1 then (1 : Rat) / 4 else 0
  let p2 := if S.contains P_World.error2 then (1 : Rat) / 4 else 0
  let p3 := if S.contains P_World.error3 then (1 : Rat) / 4 else 0
  p0 + p1 + p2 + p3

axiom preface_mu_total : ∀ (_ : P_Agent) (_ : P_World),
  preface_mu [P_World.allCorrect, P_World.error1, P_World.error2, P_World.error3] = 1
axiom preface_mu_empty : ∀ (_ : P_Agent) (_ : P_World), preface_mu [] = 0
axiom preface_c_gt_half : ∀ (_ : P_Agent), (3 : Rat) / 4 > 1 / 2
axiom preface_c_le_one : ∀ (_ : P_Agent), (3 : Rat) / 4 ≤ 1

/-- Lockean threshold `c = 3/4`. -/
def PrefaceModel : Model P_World P_Agent PrefaceAtom :=
  { worlds := [P_World.allCorrect, P_World.error1, P_World.error2, P_World.error3]
  , R := fun _ _ => [P_World.allCorrect, P_World.error1, P_World.error2, P_World.error3]
  , mu := fun _ _ => preface_mu
  , val := preface_val
  , c := fun _ => 3 / 4
  , mu_total := preface_mu_total
  , mu_empty := preface_mu_empty
  , c_gt_half := preface_c_gt_half
  , c_le_one := preface_c_le_one
  }

def p1 := Formula.prop PrefaceAtom.p1 (Ag := P_Agent)
def p2 := Formula.prop PrefaceAtom.p2 (Ag := P_Agent)
def p3 := Formula.prop PrefaceAtom.p3 (Ag := P_Agent)

def allClaims := Formula.and p1 (Formula.and p2 p3)
def someError := Formula.not allClaims

def bp1 := Formula.bel P_Agent.author p1
def bp2 := Formula.bel P_Agent.author p2
def bp3 := Formula.bel P_Agent.author p3

def bAllClaims := Formula.bel P_Agent.author allClaims
def bSomeError := Formula.bel P_Agent.author someError

/-- The author's locally accepted corpus. -/
def localAcceptance := Formula.and bp1 (Formula.and bp2 bp3)

/-- Conjunctive closure principle instantiated for the three claims. -/
def prefaceClosure := Formula.implies localAcceptance bAllClaims

/--
The central Preface configuration: the author accepts every representative
claim while also accepting that at least one representative claim is false.
This is not object-level inconsistency in FDE; it is a conflict generated by
an additional aggregation/closure principle.
-/
def prefaceConfiguration := Formula.and localAcceptance bSomeError

-- Every individual claim has positive probability 3/4, hence is believed.
#eval! eval PrefaceModel P_World.allCorrect bp1
#eval! eval PrefaceModel P_World.allCorrect bp2
#eval! eval PrefaceModel P_World.allCorrect bp3

-- Their conjunction has positive probability 1/4 and negative probability 3/4.
#eval! eval PrefaceModel P_World.allCorrect bAllClaims

-- "At least one claim is wrong" has positive probability 3/4.
#eval! eval PrefaceModel P_World.allCorrect bSomeError

-- Local acceptance survives, while conjunctive closure fails.
#eval! eval PrefaceModel P_World.allCorrect localAcceptance
#eval! eval PrefaceModel P_World.allCorrect prefaceClosure

-- The Preface configuration itself is positively supported.
#eval! eval PrefaceModel P_World.allCorrect prefaceConfiguration

end PEL4.Paradoxes
