import Lean.Elab.Tactic.Omega
import PEL4.Syntax

namespace PEL4.Paradoxes

/-!
# Signed Preface geometry

P1/P2 used only classical T/F valuations.  This module opens the genuinely
four-valued layer.  It separates two questions:

1. what threshold state is induced by positive and negative evidence masses?
2. can the same locally accepted corpus have different global joint states?

The answer to the second question is yes: at one fixed threshold, three models
below give local belief state T for every individual claim while the conjunction
has belief state F, N, or B respectively.
-/

/-- Finite four-cell evidence decomposition for one formula. -/
structure SignedMassCell where
  t : Nat
  b : Nat
  n : Nat
  f : Nat
  m : Nat
  k : Nat
  total : t + b + n + f = m

namespace SignedMassCell

def positive (s : SignedMassCell) : Nat := s.t + s.b
def negative (s : SignedMassCell) : Nat := s.f + s.b

def IsT (s : SignedMassCell) : Prop := s.k ≤ s.positive ∧ s.negative < s.k
def IsF (s : SignedMassCell) : Prop := s.positive < s.k ∧ s.k ≤ s.negative
def IsB (s : SignedMassCell) : Prop := s.k ≤ s.positive ∧ s.k ≤ s.negative
def IsN (s : SignedMassCell) : Prop := s.positive < s.k ∧ s.negative < s.k

/-- Every signed threshold profile falls into at least one of the four 4-PEL
states.  Since the defining inequalities are complementary, these are the four
exhaustive threshold regions in the positive/negative evidence plane. -/
theorem threshold_exhaustive (s : SignedMassCell) :
    s.IsT ∨ s.IsF ∨ s.IsB ∨ s.IsN := by
  unfold IsT IsF IsB IsN positive negative
  omega

/--
Any threshold glut forces overlap mass.  This is the arbitrary-denominator
counterpart of the repository's `glut_boundary_theorem`.
-/
theorem glut_overlap_bound (s : SignedMassCell) (h : s.IsB) :
    2 * s.k ≤ s.m + s.b := by
  rcases h with ⟨hpos, hneg⟩
  simp [positive, negative] at hpos hneg
  have htotal := s.total
  omega

/-- At a strict-majority threshold, a belief glut requires genuinely positive
B-mass; it cannot be generated by disjoint positive and negative evidence. -/
theorem strict_majority_glut_requires_overlap
    (s : SignedMassCell)
    (hmajority : s.m < 2 * s.k)
    (h : s.IsB) :
    0 < s.b := by
  have hb := glut_overlap_bound s h
  omega

end SignedMassCell

inductive SignedPrefaceAtom where
  | p1 | p2 | p3
deriving DecidableEq, Repr

inductive SignedPrefaceAgent where
  | author
deriving DecidableEq, Repr

inductive SignedPrefaceWorld where
  | w1 | w2 | w3 | w4 | w5
deriving DecidableEq, Repr

/-- Uniform probability on five accessible worlds. -/
def signedPrefaceMu : FiniteSet SignedPrefaceWorld → Rat
| S =>
  let q := (1 : Rat) / 5
  (if S.contains SignedPrefaceWorld.w1 then q else 0) +
  (if S.contains SignedPrefaceWorld.w2 then q else 0) +
  (if S.contains SignedPrefaceWorld.w3 then q else 0) +
  (if S.contains SignedPrefaceWorld.w4 then q else 0) +
  (if S.contains SignedPrefaceWorld.w5 then q else 0)

axiom signedPrefaceMuTotal : ∀ (_ : SignedPrefaceAgent) (_ : SignedPrefaceWorld),
  signedPrefaceMu [SignedPrefaceWorld.w1, SignedPrefaceWorld.w2,
    SignedPrefaceWorld.w3, SignedPrefaceWorld.w4, SignedPrefaceWorld.w5] = 1
axiom signedPrefaceMuEmpty : ∀ (_ : SignedPrefaceAgent) (_ : SignedPrefaceWorld),
  signedPrefaceMu [] = 0
axiom signedPrefaceThresholdGtHalf : ∀ (_ : SignedPrefaceAgent),
  (3 : Rat) / 5 > 1 / 2
axiom signedPrefaceThresholdLeOne : ∀ (_ : SignedPrefaceAgent),
  (3 : Rat) / 5 ≤ 1

/-- Build a common 3/5-threshold model from a valuation. -/
def mkSignedPrefaceModel
    (v : SignedPrefaceWorld → SignedPrefaceAtom → FDEValue) :
    Model SignedPrefaceWorld SignedPrefaceAgent SignedPrefaceAtom :=
  { worlds := [SignedPrefaceWorld.w1, SignedPrefaceWorld.w2,
      SignedPrefaceWorld.w3, SignedPrefaceWorld.w4, SignedPrefaceWorld.w5]
  , R := fun _ _ => [SignedPrefaceWorld.w1, SignedPrefaceWorld.w2,
      SignedPrefaceWorld.w3, SignedPrefaceWorld.w4, SignedPrefaceWorld.w5]
  , mu := fun _ _ => signedPrefaceMu
  , val := v
  , c := fun _ => 3 / 5
  , mu_total := signedPrefaceMuTotal
  , mu_empty := signedPrefaceMuEmpty
  , c_gt_half := signedPrefaceThresholdGtHalf
  , c_le_one := signedPrefaceThresholdLeOne
  }

/-- Classical Preface fracture: two all-correct worlds and three distinct
one-error worlds.  Every local belief is T; belief in the conjunction is F. -/
def signedFVal : SignedPrefaceWorld → SignedPrefaceAtom → FDEValue
| SignedPrefaceWorld.w1, _ => FDEValue.T
| SignedPrefaceWorld.w2, _ => FDEValue.T
| SignedPrefaceWorld.w3, SignedPrefaceAtom.p1 => FDEValue.F
| SignedPrefaceWorld.w3, _ => FDEValue.T
| SignedPrefaceWorld.w4, SignedPrefaceAtom.p2 => FDEValue.F
| SignedPrefaceWorld.w4, _ => FDEValue.T
| SignedPrefaceWorld.w5, SignedPrefaceAtom.p3 => FDEValue.F
| SignedPrefaceWorld.w5, _ => FDEValue.T

/-- Gap variant: two all-correct worlds and three distinct N-worlds.  Every
local belief remains T, while the conjunction is globally underdetermined N. -/
def signedNVal : SignedPrefaceWorld → SignedPrefaceAtom → FDEValue
| SignedPrefaceWorld.w1, _ => FDEValue.T
| SignedPrefaceWorld.w2, _ => FDEValue.T
| SignedPrefaceWorld.w3, SignedPrefaceAtom.p1 => FDEValue.N
| SignedPrefaceWorld.w3, _ => FDEValue.T
| SignedPrefaceWorld.w4, SignedPrefaceAtom.p2 => FDEValue.N
| SignedPrefaceWorld.w4, _ => FDEValue.T
| SignedPrefaceWorld.w5, SignedPrefaceAtom.p3 => FDEValue.N
| SignedPrefaceWorld.w5, _ => FDEValue.T

/-- Glut variant: two T-conjunction worlds, one B-conjunction world, and two
F-conjunction worlds.  Each individual belief is still T, but the conjunction
crosses both evidence thresholds and becomes B. -/
def signedBVal : SignedPrefaceWorld → SignedPrefaceAtom → FDEValue
| SignedPrefaceWorld.w1, _ => FDEValue.T
| SignedPrefaceWorld.w2, _ => FDEValue.T
| SignedPrefaceWorld.w3, SignedPrefaceAtom.p1 => FDEValue.B
| SignedPrefaceWorld.w3, _ => FDEValue.T
| SignedPrefaceWorld.w4, SignedPrefaceAtom.p1 => FDEValue.F
| SignedPrefaceWorld.w4, _ => FDEValue.T
| SignedPrefaceWorld.w5, SignedPrefaceAtom.p2 => FDEValue.F
| SignedPrefaceWorld.w5, _ => FDEValue.T

def SignedFModel := mkSignedPrefaceModel signedFVal
def SignedNModel := mkSignedPrefaceModel signedNVal
def SignedBModel := mkSignedPrefaceModel signedBVal

def sp1 := Formula.prop SignedPrefaceAtom.p1 (Ag := SignedPrefaceAgent)
def sp2 := Formula.prop SignedPrefaceAtom.p2 (Ag := SignedPrefaceAgent)
def sp3 := Formula.prop SignedPrefaceAtom.p3 (Ag := SignedPrefaceAgent)

def signedAllClaims := Formula.and sp1 (Formula.and sp2 sp3)
def signedSomeError := Formula.not signedAllClaims

def sbp1 := Formula.bel SignedPrefaceAgent.author sp1
def sbp2 := Formula.bel SignedPrefaceAgent.author sp2
def sbp3 := Formula.bel SignedPrefaceAgent.author sp3
def sbAllClaims := Formula.bel SignedPrefaceAgent.author signedAllClaims
def sbSomeError := Formula.bel SignedPrefaceAgent.author signedSomeError

def signedLocalAcceptance := Formula.and sbp1 (Formula.and sbp2 sbp3)

-- Same local acceptance profile in all three models.
#eval! eval SignedFModel SignedPrefaceWorld.w1 signedLocalAcceptance
#eval! eval SignedNModel SignedPrefaceWorld.w1 signedLocalAcceptance
#eval! eval SignedBModel SignedPrefaceWorld.w1 signedLocalAcceptance

-- But three distinct global states for the conjunction: F, N, B.
#eval! eval SignedFModel SignedPrefaceWorld.w1 sbAllClaims
#eval! eval SignedNModel SignedPrefaceWorld.w1 sbAllClaims
#eval! eval SignedBModel SignedPrefaceWorld.w1 sbAllClaims

-- Negation swaps T/F but fixes B/N, so the fallibility claim is T, N, B.
#eval! eval SignedFModel SignedPrefaceWorld.w1 sbSomeError
#eval! eval SignedNModel SignedPrefaceWorld.w1 sbSomeError
#eval! eval SignedBModel SignedPrefaceWorld.w1 sbSomeError

/-- The joint B control cell for `SignedBModel`: T=2, B=1, N=0, F=2,
threshold 3/5.  The overlap bound is tight: `b = 2k-m = 1`. -/
def signedBJointCell : SignedMassCell :=
  { t := 2, b := 1, n := 0, f := 2, m := 5, k := 3, total := by decide }

example : signedBJointCell.IsB := by
  constructor <;> decide

example : 0 < signedBJointCell.b := by
  apply SignedMassCell.strict_majority_glut_requires_overlap signedBJointCell
  · decide
  · constructor <;> decide

end PEL4.Paradoxes
